"""Cases 006-010."""

from casekit import case, ev, loc, search, st, sus, tl

CASES = []

# ---------------------------------------------------------------- 006
CASES.append(case(
    6, "The Museum Switch", "The frame is right. The painting is not.",
    "Medium", "gregor",
    "The Ashfield Gallery", "Art forgery and theft", "Over four days",
    "A visiting conservator notices that the varnish on the gallery's best-known "
    "portrait is wrong for its age. Analysis confirms the canvas on display is a "
    "modern replica of considerable quality. The original was last verified eleven "
    "days ago. In between, the painting left its wall exactly once, for scheduled "
    "restoration work.",
    "Gregor Melnyk, the restoration technician, made the substitution during the four "
    "days the painting was legitimately in his studio. The replica had been painted "
    "over eight months from photographs he took during earlier work. The delivery van "
    "that looked suspicious belonged to a genuine framing contractor, and the camera "
    "gap was a scheduled maintenance window that had been published internally.",
    {"studio_days": "the painting's time in the studio", "van": "the delivery van",
     "cameras": "the camera gap"},
    [
        sus("gregor", "Gregor Melnyk", 52, "Restoration technician", "Had the painting for four days",
            "Sole unsupervised access to the original, and the skill to copy it.",
            30, ["Gregor's apron", "Gregor's studio key"],
            [st("studio_days", "routine", "What happened during the four days?",
                "Routine consolidation of the lower left quadrant. Nothing else.", None, True),
             st("van", "contractor", "Whose van was at the loading bay?",
                "The framers. They come every month."),
             st("cameras", "maintenance", "Why was there a camera gap?",
                "Scheduled maintenance. It was on the internal notice board for weeks.")]),
        sus("adele", "Adele Fournier", 44, "Head curator", "Authorised the restoration",
            "Signed the movement order and holds the only other studio key.",
            35, ["Adele's key ring"],
            [st("studio_days", "supervised", "What happened during the four days?",
                "It was signed in and signed out. I checked it myself on the Friday."),
             st("van", "contractor", "Whose van was at the loading bay?",
                "Ashfield Framing. They have held our contract for six years."),
             st("cameras", "maintenance", "Why was there a camera gap?",
                "The upgrade. It was announced. I was in Lyon for all of it.")]),
        sus("tomas", "Tomas Reyes", 27, "Gallery attendant", "On the floor every day",
            "In debt, and has been seen photographing works after hours.",
            40, ["Tomas's phone"],
            [st("studio_days", "unknown", "What happened during the four days?",
                "I would not know. Attendants do not go into the studio."),
             st("van", "unfamiliar", "Whose van was at the loading bay?",
                "There was one I did not recognise on the Wednesday. No livery on it."),
             st("cameras", "unknown", "Why was there a camera gap?",
                "Nobody tells me anything about the cameras.")]),
        sus("nell", "Nell Harkness", 39, "Registrar", "Keeps the movement records",
            "Was disciplined last year for falsifying a loan document.",
            35, ["Nell's document case"],
            [st("studio_days", "documented", "What happened during the four days?",
                "In on the Monday, out on the Friday, both signed. I have the sheets."),
             st("van", "contractor", "Whose van was at the loading bay?",
                "Ashfield Framing, booked and logged. Wednesday, eleven o'clock."),
             st("cameras", "maintenance", "Why was there a camera gap?",
                "The upgrade window. Published, scheduled, boring.")]),
    ],
    [
        loc("gallery", "Main Gallery", "[G]",
            "The portrait hangs where it always has, under a light that has not moved in decades.",
            [search("canvas", "Examine the canvas", ["e01"], "Modern ground, modern varnish, and an old frame."),
             search("frame", "Examine the frame", ["e02"], "Original. Whoever did this kept the frame.")]),
        loc("studio", "Restoration Studio", "[T]",
            "Solvent, raking light, and a bench that has been very carefully cleaned.",
            [search("bench", "Search the bench", ["e03"], "Pigment traces that should not exist in a conservation studio."),
             search("photos", "Look through the reference photographs", ["e04"], "Eight months of raking-light captures."),
             search("waste", "Search the waste", ["e05"], "Offcuts of primed modern linen.")]),
        loc("bay", "Loading Bay", "[B]",
            "Where everything enters and leaves, under a camera that mostly works.",
            [search("bookings", "Check the delivery bookings", ["e06"], "One booked van, and one that was not."),
             search("baycam", "Review the bay camera", ["e07"], "Wednesday, eleven o'clock, exactly as booked.")]),
        loc("records", "Registrar's Office", "[R]",
            "Movement sheets, condition reports, and a filing system with opinions.",
            [search("movement", "Read the movement sheets", ["e08"], "Signed in and out, in two different hands."),
             search("condition", "Compare the condition reports", ["e09"], "The Friday report describes a painting that is not this one.")]),
        loc("control", "Camera Control Room", "[C]",
            "The gap in the record, and the paperwork that explains it.",
            [search("gap", "Examine the camera gap", ["e10"], "Four hours, on the Wednesday."),
             search("notice", "Find the maintenance notice", ["e11"], "Circulated three weeks in advance.")]),
    ],
    [
        ev("e01", "Modern canvas ground", "The canvas on the wall uses a ground unavailable before 1960.",
           "PHYSICAL", 100, 8),
        ev("e02", "Original frame retained", "The frame is authentic, so the swap happened out of the frame.",
           "PHYSICAL", 96, 10, "gregor"),
        ev("e03", "Pigment traces on the bench", "Modern pigments matching the replica, on the studio bench.",
           "PHYSICAL", 93, 28, "gregor"),
        ev("e04", "Eight months of reference photographs", "Raking-light captures of the original, taken long before the restoration.",
           "DIGITAL", 95, 30, "gregor"),
        ev("e05", "Primed linen offcuts", "Offcuts of modern primed linen in the studio waste.",
           "PHYSICAL", 88, 22, "gregor"),
        ev("e06", "Unbooked van", "A van with no livery at the bay on Wednesday, not in the booking sheet.",
           "DOCUMENT", 80, 20, "tomas", rh=True, cleared_by="e07"),
        ev("e07", "Bay camera footage", "The Wednesday van is Ashfield Framing, on its regular monthly booking.",
           "DIGITAL", 97, 0),
        ev("e08", "Movement sheets", "The painting was signed into the studio on Monday and out on Friday.",
           "DOCUMENT", 100, 12, "gregor"),
        ev("e09", "Divergent condition report", "The Friday report describes craquelure that the displayed canvas does not have.",
           "DOCUMENT", 94, 26, "gregor"),
        ev("e10", "Camera maintenance gap", "Four hours of no recording on the Wednesday afternoon.",
           "DIGITAL", 100, 15, "adele", rh=True, cleared_by="e11"),
        ev("e11", "Maintenance notice", "The camera window was published internally three weeks in advance.",
           "DOCUMENT", 100, 0),
        ev("e12", "Photograph metadata", "The reference photographs were taken on the studio's own camera, at night.",
           "DIGITAL", 98, 32, "gregor", requires=["e04", "e03"]),
    ],
    [
        tl("Day 1, Mon", "The portrait is signed into the restoration studio."),
        tl("Day 3, Wed 11:00", "A framing van uses the loading bay.", True, "e07"),
        tl("Day 3, Wed 13:00", "The camera maintenance window begins.", True, "e10"),
        tl("Day 3, Wed 17:00", "The camera maintenance window ends."),
        tl("Day 5, Fri", "The painting is signed out and rehung.", True, "e08"),
        tl("Day 16", "A visiting conservator questions the varnish."),
    ],
    ["The frame was never taken. Ask what that means about where the swap happened.",
     "Two things look suspicious and both have paperwork. Check the paperwork.",
     "A copy that good was not made in four days."],
))

# ---------------------------------------------------------------- 007
CASES.append(case(
    7, "The Anonymous Letters", "Six letters, one hand",
    "Medium", "roland",
    "Kerrigan Haulage", "Criminal harassment", "Over nine weeks",
    "Fiona Kerrigan, who runs a haulage firm, has received six anonymous letters over "
    "nine weeks. They are typed, unsigned, and increasingly specific about her "
    "movements. The most recent describes the interior of her home office. The police "
    "want the sender identified before the threats escalate.",
    "Roland Petrie, the firm's bookkeeper, wrote all six. He had been moving small "
    "sums out of the accounts for three years and began the letters when Fiona "
    "commissioned an external audit. The details of her home office came from a "
    "quotation visit he made for the firm's insurance renewal. His attempt to disguise "
    "his writing failed on a spelling habit and a printer that leaves a signature.",
    {"letters": "the anonymous letters", "office_visit": "who has been in her home office",
     "audit": "the external audit"},
    [
        sus("roland", "Roland Petrie", 58, "Bookkeeper", "Twenty years with the firm",
            "Three years of small unexplained withdrawals, about to be audited.",
            25, ["Roland's desk printer", "Roland's notebook"],
            [st("letters", "no_knowledge", "What do you know about the letters?",
                "Only what Fiona has told the office. It is a dreadful business.", None, True),
             st("office_visit", "never", "Have you been in her home office?",
                "Never. I have not set foot in that house.", "e07", True),
             st("audit", "welcome", "How do you feel about the external audit?",
                "It is overdue, frankly. I have been asking for one for years.", None, True)]),
        sus("declan", "Declan Fry", 34, "Yard supervisor", "Manages the drivers",
            "Was formally warned by Fiona a fortnight before the first letter.",
            40, ["Declan's van keys"],
            [st("letters", "no_knowledge", "What do you know about the letters?",
                "I heard about them in the canteen. That is all."),
             st("office_visit", "once", "Have you been in her home office?",
                "Once, last winter, to drop off keys. I stood in the doorway."),
             st("audit", "indifferent", "How do you feel about the external audit?",
                "It does not touch the yard. Good luck to them.")]),
        sus("mairead", "Mairead Kerrigan", 47, "Co-director", "The victim's sister-in-law",
            "Disagreed publicly with Fiona over selling the firm.",
            35, ["Mairead's laptop"],
            [st("letters", "seen_them", "What do you know about the letters?",
                "I have read three of them. They are written by somebody who knows the accounts."),
             st("office_visit", "often", "Have you been in her home office?",
                "Constantly. We do half our board business at her kitchen table."),
             st("audit", "supportive", "How do you feel about the external audit?",
                "I asked for it. Fiona resisted for months.")]),
        sus("bridget", "Bridget Nolan", 30, "Office administrator", "Handles the post",
            "Opens every letter that arrives, including these.",
            30, ["Bridget's cardigan"],
            [st("letters", "opened", "What do you know about the letters?",
                "I opened four of them. I wish I had not."),
             st("office_visit", "never", "Have you been in her home office?",
                "No. I have never been to the house."),
             st("audit", "indifferent", "How do you feel about the external audit?",
                "It means more filing for me. That is my entire opinion.")]),
    ],
    [
        loc("letters", "The Letters", "[L]",
            "Six sheets in evidence bags, laid out in order of receipt.",
            [search("text", "Analyse the wording", ["e01"], "The same word misspelled the same way, six times."),
             search("paper", "Examine the paper stock", ["e02"], "A watermark used by one supplier in the county."),
             search("print", "Examine the print quality", ["e03"], "A repeating defect down the right margin.")]),
        loc("postmark", "Postal Records", "[P]",
            "Six postmarks, four sorting offices, one pattern.",
            [search("marks", "Plot the postmarks", ["e04"], "All six posted within a mile of one address."),
             search("times", "Check the collection times", ["e05"], "Every one caught the 5:15 PM collection.")]),
        loc("officefirm", "The Firm's Office", "[O]",
            "Four desks, four printers, and a stationery cupboard nobody locks.",
            [search("printers", "Test the office printers", ["e06"], "One machine reproduces the margin defect exactly."),
             search("stationery", "Check the stationery order", ["e08"], "Who ordered the watermarked stock, and when.")]),
        loc("home", "Fiona's Home Office", "[H]",
            "The room described in the sixth letter, in detail that should not be available.",
            [search("visitors", "Check the visitor book", ["e07"], "An insurance quotation visit, five weeks ago."),
             search("details", "Compare the letter to the room", ["e09"], "Three details visible only from one chair.")]),
        loc("accounts", "Accounts Ledger", "[A]",
            "Three years of entries and a set of round numbers that recur.",
            [search("ledger", "Examine the ledger", ["e10"], "Small withdrawals, always under the review threshold."),
             search("auditfile", "Read the audit scope", ["e11"], "The audit would have opened exactly those accounts.")]),
    ],
    [
        ev("e01", "Repeated misspelling", "The same uncommon misspelling appears in all six letters.",
           "DOCUMENT", 91, 18, "roland"),
        ev("e02", "Watermarked paper", "The paper carries a watermark from a single regional supplier.",
           "PHYSICAL", 88, 12),
        ev("e03", "Printer margin defect", "A repeating defect down the right margin of every letter.",
           "PHYSICAL", 94, 20, "roland"),
        ev("e04", "Postmark cluster", "All six letters were posted within a mile of the same address.",
           "DOCUMENT", 86, 14, "declan", rh=True, cleared_by="e06"),
        ev("e05", "Collection time pattern", "Every letter caught the 5:15 PM collection, just after office hours.",
           "DOCUMENT", 90, 10),
        ev("e06", "Printer match", "The margin defect is reproduced exactly by the bookkeeper's desk printer.",
           "PHYSICAL", 97, 30, "roland", matches=["Roland's desk printer"]),
        ev("e07", "Insurance visit record", "Roland attended a quotation visit to the house five weeks ago.",
           "DOCUMENT", 95, 26, "roland"),
        ev("e08", "Stationery order", "The watermarked stock was ordered by the accounts desk in March.",
           "DOCUMENT", 89, 20, "roland"),
        ev("e09", "Sightline detail", "The sixth letter describes three details visible only from the chair by the window.",
           "TESTIMONY", 80, 16, "roland"),
        ev("e10", "Irregular withdrawals", "Three years of small withdrawals, each just under the review threshold.",
           "DOCUMENT", 96, 22, "roland"),
        ev("e11", "Audit scope document", "The commissioned audit would have opened the exact accounts affected.",
           "DOCUMENT", 93, 0),
        ev("e12", "Handwriting on the notebook", "The bookkeeper's notebook carries the same misspelling, unguarded.",
           "DOCUMENT", 98, 32, "roland", requires=["e01", "e10"]),
    ],
    [
        tl("Week 1", "Fiona commissions an external audit."),
        tl("Week 2", "The first letter arrives."),
        tl("Week 4", "The letters begin describing her movements."),
        tl("Week 5", "An insurance quotation visit takes place at the house.", True, "e07"),
        tl("Week 7", "The sixth letter describes the interior of the home office.", True, "e09"),
        tl("Week 9", "The audit fieldwork is scheduled to begin."),
    ],
    ["The writer tried to disguise their style but not their spelling.",
     "Printers leave a signature. Find the machine, not the person.",
     "Ask who had a reason to want the audit stopped."],
))

# ---------------------------------------------------------------- 008
CASES.append(case(
    8, "The Midnight Express", "A passenger who was never on board",
    "Expert", "conductor",
    "The overnight express, Carlisle to Inverness", "Disappearance", "12:10 AM - 4:30 AM",
    "A sleeper compartment is found empty at Inverness. The ticket was collected, the "
    "bunk was slept in, the door was locked from inside, and the passenger, Hugh "
    "Aylward, is not on the train. Every external door was sealed between Carlisle and "
    "the first stop. The window in the compartment does not open far enough for a "
    "person to pass through.",
    "Aylward never boarded. His brother-in-law, the conductor Frank Doyle, collected "
    "the ticket, rumpled the bunk, and locked the compartment from the corridor with a "
    "staff key that leaves the internal bolt engaged. Aylward was already dead in "
    "Carlisle, and the impossible disappearance was manufactured to place the death on "
    "a moving train and outside the jurisdiction that was investigating him.",
    {"boarding": "whether the passenger boarded", "compartment": "the locked compartment",
     "keys": "who holds a staff key"},
    [
        sus("conductor", "Frank Doyle", 56, "Conductor", "Collected the ticket",
            "Married to the missing man's sister, and named in the same investigation.",
            30, ["Frank's staff key", "Frank's ticket punch"],
            [st("boarding", "boarded", "Did the passenger board?",
                "He boarded at Carlisle. I clipped his ticket myself on the platform.", None, True),
             st("compartment", "locked_inside", "How was the compartment secured?",
                "Bolted from within. I had to use the emergency release at Inverness.", None, True),
             st("keys", "several", "Who holds a staff key?",
                "Myself, the sleeper attendant, and the guard. Three of us.")]),
        sus("attendant", "Rosa Lind", 34, "Sleeper attendant", "Serviced the carriage",
            "Was disciplined after a complaint made by the missing man last year.",
            35, ["Rosa's service trolley"],
            [st("boarding", "not_seen", "Did the passenger board?",
                "I never saw him. I saw a made bunk and a closed door and I left it alone."),
             st("compartment", "closed_early", "How was the compartment secured?",
                "The door was shut before we left Carlisle. That is unusual, they normally settle in slowly."),
             st("keys", "several", "Who holds a staff key?",
                "Three of us on this service. Frank, myself, and the guard.")]),
        sus("guard", "Alec Munro", 61, "Train guard", "Sealed the external doors",
            "Signed the seal record that makes the disappearance impossible.",
            30, ["Alec's seal log"],
            [st("boarding", "not_seen", "Did the passenger board?",
                "I was at the rear. I would not see a boarding at coach C."),
             st("compartment", "unknown", "How was the compartment secured?",
                "I did not go near it until Inverness."),
             st("keys", "several", "Who holds a staff key?",
                "The three of us. Mine has not left my belt.")]),
        sus("sister", "Moira Doyle", 52, "The missing man's sister", "Travelling in coach A",
            "Inherits control of a disputed family trust.",
            25, ["Moira's travelling case"],
            [st("boarding", "boarded", "Did the passenger board?",
                "Frank told me Hugh was aboard. I did not see him myself."),
             st("compartment", "unknown", "How was the compartment secured?",
                "I have no idea. I was four carriages away."),
             st("keys", "none", "Who holds a staff key?",
                "I am a passenger. I hold a ticket.")]),
    ],
    [
        loc("compartment", "Compartment C7", "[7]",
            "A slept-in bunk, a locked door, and a window that opens four inches.",
            [search("bunk", "Examine the bunk", ["e01"], "Rumpled from above, not slept in from within."),
             search("bolt", "Examine the internal bolt", ["e02"], "Engaged, with a fresh scrape on the housing."),
             search("windowc", "Examine the window", ["e03"], "Four inches, and the restraint is undamaged.")]),
        loc("corridor", "Coach C Corridor", "[C]",
            "The passage outside C7, and the only route to the door.",
            [search("keyhole", "Examine the corridor lock", ["e04"], "A staff key can throw the internal bolt from outside."),
             search("witness", "Ask the neighbouring passengers", ["e05"], "Nobody in C6 or C8 heard anyone arrive.")]),
        loc("platform", "Carlisle Platform", "[P]",
            "Where the train stood for eleven minutes at ten past midnight.",
            [search("platcam", "Review the platform camera", ["e06"], "Every boarding passenger, and not one of them is Aylward."),
             search("ticketrec", "Check the ticket collection record", ["e07"], "Clipped at 12:08 AM, at the barrier.")]),
        loc("guardvan", "Guard's Van", "[G]",
            "Seals, logs, and the paperwork that makes the train a sealed box.",
            [search("seals", "Check the door seals", ["e08"], "Intact, every one, all the way to Inverness."),
             search("keylog", "Read the key sign-out log", ["e09"], "Three keys, and one entry altered.")]),
        loc("carlisle", "Carlisle Sidings", "[S]",
            "Where the search was extended after the second day.",
            [search("sidings", "Search the sidings", ["e10"], "A discarded overcoat, well away from the platform."),
             search("phone", "Trace the passenger's phone", ["e11"], "It never left Carlisle.")]),
    ],
    [
        ev("e01", "Bunk disturbed from above", "The bedding was rumpled by hand rather than slept in.",
           "PHYSICAL", 87, 20, "conductor"),
        ev("e02", "Scrape on the bolt housing", "Fresh tooling marks where the internal bolt meets its housing.",
           "PHYSICAL", 90, 22, "conductor"),
        ev("e03", "Intact window restraint", "The window opens four inches and the restraint is undamaged.",
           "PHYSICAL", 100, 6),
        ev("e04", "Staff key mechanism", "A staff key can throw the internal bolt from the corridor side.",
           "PHYSICAL", 96, 25, "conductor"),
        ev("e05", "Neighbouring passengers", "Nobody in C6 or C8 heard anyone enter C7 at any point.",
           "TESTIMONY", 74, 12),
        ev("e06", "Platform camera", "The platform camera records every boarding, and Aylward is not among them.",
           "DIGITAL", 98, 30, "conductor"),
        ev("e07", "Ticket collection record", "The ticket was clipped at the barrier at 12:08 AM.",
           "DOCUMENT", 95, 24, "conductor"),
        ev("e08", "Intact door seals", "Every external door seal is unbroken from Carlisle to Inverness.",
           "PHYSICAL", 100, 8),
        ev("e09", "Altered key log", "One entry in the key sign-out log has been overwritten.",
           "DOCUMENT", 89, 26, "conductor"),
        ev("e10", "Discarded overcoat", "The missing man's overcoat, found in the Carlisle sidings.",
           "PHYSICAL", 84, 10),
        ev("e11", "Phone location record", "The passenger's phone never moved out of Carlisle.",
           "DIGITAL", 99, 28, "conductor"),
        ev("e12", "Shared investigation file", "The conductor is named alongside the missing man in an ongoing enquiry.",
           "DOCUMENT", 93, 30, "conductor", requires=["e06", "e11"]),
    ],
    [
        tl("12:08 AM", "A ticket in Aylward's name is clipped at the barrier.", True, "e07"),
        tl("12:10 AM", "The train departs Carlisle."),
        tl("12:14 AM", "The door of C7 is observed already closed.", True, "e05"),
        tl("01:00 AM", "External door seals are checked and recorded intact."),
        tl("04:30 AM", "The train arrives at Inverness."),
        tl("04:38 AM", "C7 is opened with the emergency release."),
    ],
    ["An impossible disappearance is usually an impossible arrival.",
     "Check whether the passenger was ever recorded boarding, not merely ticketed.",
     "Ask what a staff key can do that a passenger key cannot."],
))

# ---------------------------------------------------------------- 009
CASES.append(case(
    9, "The Clinic Ledger", "A drug count that will not reconcile",
    "Medium", "sister",
    "St Brendan's Community Clinic", "Systematic theft", "Over five months",
    "A routine inspection finds that the clinic's controlled drug register does not "
    "match its stock. The shortfall has been accumulating for five months and is "
    "large enough to be criminal rather than clerical. Four members of staff hold "
    "cabinet access. All four have signed entries in the register.",
    "Sister Anne Cavanagh had been signing out doses for a patient who was discharged "
    "in March, using a paper record that was never reconciled against the electronic "
    "discharge list. Doctor Whelan's unusual prescribing pattern was a genuine "
    "clinical decision, documented in notes nobody had read, and the agency nurse's "
    "missing signature was an administrative failure rather than a theft.",
    {"cabinet": "who accessed the cabinet", "discharge": "the discharged patient",
     "register": "the register entries"},
    [
        sus("sister", "Sister Anne Cavanagh", 49, "Senior nurse", "Holds the cabinet key on days",
            "Reconciles the paper register against nothing at all.",
            25, ["Anne's key fob", "Anne's clipboard"],
            [st("cabinet", "routine", "Who accessed the cabinet?",
                "All four of us, as the rota requires. Nothing unusual."),
             st("discharge", "unaware", "Was a discharged patient still being dosed?",
                "Certainly not. We reconcile against the ward list every morning.", "e05", True),
             st("register", "accurate", "Are the register entries accurate?",
                "They are signed and countersigned. I would stake my career on them.", None, True)]),
        sus("whelan", "Dr Patrick Whelan", 57, "General practitioner", "Prescribes for the clinic",
            "His prescribing volume is well above the regional average.",
            40, ["Dr Whelan's prescription pad"],
            [st("cabinet", "rarely", "Who accessed the cabinet?",
                "I sign, I do not dispense. My name is on prescriptions, not the cabinet."),
             st("discharge", "unaware", "Was a discharged patient still being dosed?",
                "If so, nobody told me, and I would want to know."),
             st("register", "not_my_area", "Are the register entries accurate?",
                "That is nursing's book, not mine.")]),
        sus("agency", "Kelly Duarte", 28, "Agency nurse", "Covers three nights a week",
            "Two of her shifts have register entries with no countersignature.",
            35, ["Kelly's agency badge"],
            [st("cabinet", "nights", "Who accessed the cabinet?",
                "Me, on nights, with whoever is second on. That is the rule."),
             st("discharge", "unaware", "Was a discharged patient still being dosed?",
                "I dose from the chart in front of me. I do not check discharges."),
             st("register", "gaps", "Are the register entries accurate?",
                "Two of mine have no countersignature. I raised it and nothing happened.")]),
        sus("pharm", "Owen Bradach", 43, "Dispensing pharmacist", "Orders the stock",
            "Placed three replacement orders without a matching usage record.",
            30, ["Owen's order book"],
            [st("cabinet", "deliveries", "Who accessed the cabinet?",
                "I load it on delivery days. I do not remove from it."),
             st("discharge", "unaware", "Was a discharged patient still being dosed?",
                "I would not see that. I see quantities, not patients."),
             st("register", "mismatch", "Are the register entries accurate?",
                "They cannot be. I have ordered more than the register says was used.")]),
    ],
    [
        loc("cabinet", "Controlled Drug Cabinet", "[K]",
            "A steel cabinet, a paper register, and a fob reader that logs everything.",
            [search("registerbook", "Read the paper register", ["e01"], "Neat, complete, and internally consistent."),
             search("fob", "Pull the fob access log", ["e02"], "Times that do not always match the register."),
             search("count", "Count the remaining stock", ["e03"], "The shortfall, quantified.")]),
        loc("ward", "Ward Records", "[W]",
            "Charts, discharge lists, and two systems that were never made to talk.",
            [search("discharges", "Compare the discharge list", ["e05"], "One name that keeps receiving doses."),
             search("charts", "Read the drug charts", ["e04"], "Entries in a familiar hand, after a familiar date.")]),
        loc("dispensary", "Dispensary", "[D]",
            "Deliveries in, prescriptions out, and an order book with strong opinions.",
            [search("orders", "Examine the order book", ["e06"], "Three replacement orders with no usage to justify them."),
             search("scripts", "Review the prescribing pattern", ["e07"], "High volume, and a reason nobody has read.")]),
        loc("notes", "Clinical Notes Archive", "[N]",
            "Where the reason for anything is written down and then never opened again.",
            [search("clinical", "Read the clinical justification", ["e08"], "A documented decision, fully reasoned."),
             search("incident", "Search the incident reports", ["e09"], "A countersignature failure, reported twice.")]),
        loc("rota", "Staff Rota Office", "[R]",
            "Who was on, when, and who was supposed to be watching them.",
            [search("rotafile", "Cross-check the rota", ["e10"], "Every unexplained entry falls in one shift pattern.")]),
    ],
    [
        ev("e01", "Paper register", "The paper register is complete, consistent, and reconciles with itself.",
           "DOCUMENT", 100, 6),
        ev("e02", "Fob access log", "Cabinet access times that do not always correspond to register entries.",
           "DIGITAL", 96, 18, "sister"),
        ev("e03", "Stock shortfall", "The physical count is substantially below the register's figure.",
           "PHYSICAL", 100, 8),
        ev("e04", "Post-discharge dosing entries", "Doses recorded for a patient discharged in March, in one hand.",
           "DOCUMENT", 97, 32, "sister"),
        ev("e05", "Discharge list", "The patient in question was discharged on the eleventh of March.",
           "DOCUMENT", 100, 20, "sister"),
        ev("e06", "Unjustified replacement orders", "Three replacement orders with no corresponding recorded usage.",
           "DOCUMENT", 92, 16, "pharm", rh=True, cleared_by="e03"),
        ev("e07", "High prescribing volume", "Dr Whelan prescribes well above the regional average.",
           "DOCUMENT", 90, 20, "whelan", rh=True, cleared_by="e08"),
        ev("e08", "Clinical justification", "A documented, reasoned clinical basis for the prescribing pattern.",
           "DOCUMENT", 98, 0),
        ev("e09", "Countersignature incident reports", "The agency nurse reported missing countersignatures twice.",
           "DOCUMENT", 94, 15, "agency", rh=True, cleared_by="e02"),
        ev("e10", "Rota cross-check", "Every unexplained cabinet access falls on the senior nurse's shift pattern.",
           "DOCUMENT", 95, 26, "sister"),
        ev("e11", "Handwriting on the charts", "The post-discharge entries are in the senior nurse's hand.",
           "DOCUMENT", 96, 30, "sister", requires=["e04", "e10"]),
    ],
    [
        tl("11 March", "A patient is discharged from the clinic.", True, "e05"),
        tl("14 March", "Dosing entries continue for that patient.", True, "e04"),
        tl("April", "The first replacement order is placed."),
        tl("May", "An agency nurse reports missing countersignatures.", True, "e09"),
        tl("June", "A second replacement order is placed."),
        tl("July", "A routine inspection identifies the shortfall."),
    ],
    ["The register reconciles with itself. Compare it against something else.",
     "Two suspicious patterns have documented explanations. Find the one that does not.",
     "Ask whether every patient being dosed was still a patient."],
))

# ---------------------------------------------------------------- 010
CASES.append(case(
    10, "The Bidder in the Room", "A sealed tender that leaked",
    "Hard", "priyanka",
    "Northgate City Council", "Corruption", "Over three weeks",
    "A construction contract worth eleven million is awarded to a bidder who undercut "
    "the nearest rival by four thousand pounds. The tenders were sealed and held in a "
    "safe until the opening. The margin is too fine to be coincidence, and an "
    "anonymous complaint alleges the winning bidder saw a rival figure in advance.",
    "Priyanka Basu, the procurement officer, photographed the rival submission during "
    "the compliance check that only she performed, and passed the figure through her "
    "brother-in-law who works for the winning bidder. The safe access log that "
    "implicated the committee chair was a legitimate audit inspection, and the "
    "consultant's late-night building entry was for an unrelated project.",
    {"safe": "access to the safe", "compliance": "the compliance check",
     "contact": "contact with the bidders"},
    [
        sus("priyanka", "Priyanka Basu", 36, "Procurement officer", "Ran the tender process",
            "Sole custody of the submissions during the compliance check.",
            25, ["Priyanka's work phone", "Priyanka's lanyard"],
            [st("safe", "logged", "Who accessed the safe?",
                "Only as logged. The log is the whole point of the log."),
             st("compliance", "standard", "Describe the compliance check.",
                "Standard. Envelopes opened, forms checked for completeness, resealed.", None, True),
             st("contact", "none", "Any contact with the bidders?",
                "None outside the formal clarification process. That would be improper.", "e08", True)]),
        sus("chair", "Councillor Ray Hollis", 61, "Committee chair", "Chaired the award",
            "His access card opened the safe room out of hours.",
            40, ["Ray's access card"],
            [st("safe", "audit", "Who accessed the safe?",
                "I attended an audit inspection. It was booked, witnessed and minuted."),
             st("compliance", "not_present", "Describe the compliance check.",
                "I am not present for that. Members are kept out of it deliberately."),
             st("contact", "declared", "Any contact with the bidders?",
                "I declared a social contact with one director eight months ago. It is on the register.")]),
        sus("consultant", "Fiona Marr", 44, "External consultant", "Advised on the specification",
            "Entered the building at 10:40 PM during the tender window.",
            35, ["Fiona's visitor pass"],
            [st("safe", "no_access", "Who accessed the safe?",
                "I have no safe access. I am not staff."),
             st("compliance", "not_present", "Describe the compliance check.",
                "Not my role. I wrote the specification and left."),
             st("contact", "professional", "Any contact with the bidders?",
                "I have worked with two of them on other schemes. All declared.")]),
        sus("clerk", "Dermot Quill", 29, "Committee clerk", "Minutes the meetings",
            "Handled the envelopes between the safe and the committee room.",
            30, ["Dermot's satchel"],
            [st("safe", "escorted", "Who accessed the safe?",
                "I carry the envelopes, always escorted, always signed."),
             st("compliance", "not_present", "Describe the compliance check.",
                "I hand them over and I get them back. I do not open anything."),
             st("contact", "none", "Any contact with the bidders?",
                "None whatsoever.")]),
    ],
    [
        loc("safe", "Tender Safe Room", "[S]",
            "One safe, one card reader, and a log that is taken very seriously.",
            [search("safelog", "Read the safe access log", ["e01"], "Three accesses in the window, all logged."),
             search("audit", "Check the audit booking", ["e02"], "Booked, witnessed and minuted.")]),
        loc("compliance", "Compliance Room", "[C]",
            "Where sealed envelopes are opened, checked and resealed by one person alone.",
            [search("envelopes", "Examine the resealed envelopes", ["e03"], "One reseal is not quite square."),
             search("cctvc", "Review the compliance room camera", ["e04"], "The camera faces the door, not the table."),
             search("desk", "Search the desk", ["e05"], "A phone stand, angled at the table.")]),
        loc("network", "Council Network", "[N]",
            "Where every device that touches the building leaves a trace.",
            [search("uploads", "Trace outbound transfers", ["e06"], "One image upload at 4:12 PM."),
             search("devices", "Identify the device", ["e07"], "A work phone, in the compliance room.")]),
        loc("registers", "Interests Register", "[I]",
            "Declared relationships, and the ones that were not declared.",
            [search("declared", "Read the declared interests", ["e09"], "Two declarations, both current."),
             search("undeclared", "Cross-check employment records", ["e08"], "A relative, at the winning bidder.")]),
        loc("entryrec", "Building Entry Records", "[E]",
            "Who came in, when, and on whose pass.",
            [search("late", "Check late entries", ["e10"], "One at 10:40 PM, and a project code that explains it.")]),
    ],
    [
        ev("e01", "Safe access log", "Three logged accesses to the safe during the tender window.",
           "DIGITAL", 100, 12, "chair", rh=True, cleared_by="e02"),
        ev("e02", "Audit booking record", "The chair's access was a booked, witnessed audit inspection.",
           "DOCUMENT", 98, 0),
        ev("e03", "Imperfect reseal", "One envelope has been opened and resealed slightly out of square.",
           "PHYSICAL", 86, 22, "priyanka"),
        ev("e04", "Compliance room camera", "The camera covers the door but not the working table.",
           "DIGITAL", 100, 6),
        ev("e05", "Phone stand on the desk", "A phone stand positioned to view the working table.",
           "PHYSICAL", 78, 20, "priyanka"),
        ev("e06", "Outbound image transfer", "An image was uploaded from the council network at 4:12 PM.",
           "DIGITAL", 95, 26, "priyanka"),
        ev("e07", "Device identification", "The upload came from a work phone assigned to the procurement officer.",
           "DIGITAL", 97, 30, "priyanka"),
        ev("e08", "Undeclared relative", "A relative of the procurement officer is employed by the winning bidder.",
           "DOCUMENT", 94, 32, "priyanka"),
        ev("e09", "Declared interests", "The chair and the consultant have both declared their contacts.",
           "DOCUMENT", 100, 0),
        ev("e10", "Late building entry", "The consultant entered at 10:40 PM under an unrelated project code.",
           "DOCUMENT", 92, 18, "consultant", rh=True, cleared_by="e09"),
        ev("e11", "Transfer recipient", "The uploaded image was received by an address at the winning bidder.",
           "DIGITAL", 96, 34, "priyanka", requires=["e06", "e08"]),
    ],
    [
        tl("Day 1", "Tenders are received and placed in the safe."),
        tl("Day 4, 10:40 PM", "A consultant enters the building.", True, "e10"),
        tl("Day 6, 2:00 PM", "The compliance check begins."),
        tl("Day 6, 4:12 PM", "An image is uploaded from the council network.", True, "e06"),
        tl("Day 9", "An audit inspection accesses the safe.", True, "e02"),
        tl("Day 14", "The winning bid is submitted, four thousand pounds under."),
        tl("Day 21", "The contract is awarded."),
    ],
    ["Two people look suspicious and both have paperwork that clears them.",
     "The camera covers the door. Ask what it does not cover.",
     "Follow the image, not the envelope."],
))
