"""Cases 001-005."""

from casekit import case, ev, loc, search, st, sus, tl

CASES = []

# ---------------------------------------------------------------- 001
CASES.append(case(
    1, "The Missing Diamond", "Blackwood Mansion, a private party, and an empty case",
    "Medium", "sophia",
    "Blackwood Mansion", "Theft", "10:15 PM - 10:45 PM",
    "The Blackwood family is hosting a private celebration. The Blackwood Diamond, "
    "valued at around two million dollars, sits in a protected exhibition case. At "
    "10:15 PM it is confirmed present. At 10:45 PM a member of staff finds the case "
    "open and the stone gone. There is no forced entry, and only a handful of people "
    "had access to that wing of the house.",
    "Sophia Miller left the dining hall at 10:26 PM, used a panel code she had "
    "memorised while filing Mr Blackwood's insurance paperwork, and opened the "
    "display without triggering an alarm. A button tore from her coat as she reached "
    "into the case. The camera outage that made Marcus Reed look guilty was an "
    "automated firmware restart, scheduled months earlier and pure coincidence.",
    {"location_2230": "location at 10:30 PM", "last_saw": "when they last saw the diamond",
     "panel_code": "knowledge of the panel code"},
    [
        sus("adrian", "Adrian Blackwood", 31, "Business executive", "Son of the owner",
            "Carries significant private debt and knows exactly what the stone is worth.",
            30, ["Adrian's dinner jacket"],
            [st("location_2230", "dining_hall", "Where were you at 10:30 PM?",
                "In the dining hall, arguing with my father about money. Half the room heard it."),
             st("last_saw", "before_dinner", "When did you last see the diamond?",
                "Before dinner. I walked guests past the case at eight."),
             st("panel_code", "no", "Do you know the code for the display panel?",
                "No. My father never trusted me with it, which tells you something.")]),
        sus("sophia", "Sophia Miller", 28, "Personal assistant", "Works directly for Mr Blackwood",
            "Was told last week that her contract would not be renewed.",
            20, ["Sophia's grey coat", "Sophia's handbag"],
            [st("location_2230", "dining_hall", "Where were you at 10:30 PM?",
                "In the dining room. I did not leave it once between ten and the alarm.", None, True),
             st("last_saw", "ten_fifteen", "When did you last see the diamond?",
                "At quarter past ten. I checked the room before the toast."),
             st("panel_code", "no", "Do you know the code for the display panel?",
                "Certainly not. That is Mr Reed's department, not mine.", None, True),
             st("coat", "intact", "Is there a button missing from your coat?",
                "I really could not say. Coats lose buttons. Is that a crime now?", "e01")]),
        sus("marcus", "Marcus Reed", 42, "Security supervisor", "Responsible for the house system",
            "Understands the alarm system better than anyone in the building.",
            50, ["Marcus's uniform jacket"],
            [st("location_2230", "security_room", "Where were you at 10:30 PM?",
                "In the security room watching the feeds go dark one after another."),
             st("last_saw", "ten_fifteen", "When did you last see the diamond?",
                "On the monitor at ten fifteen. Then the corridor camera dropped."),
             st("panel_code", "yes", "Do you know the code for the display panel?",
                "Of course I do. So does the insurer, and so does the file it is written in.")]),
        sus("elena", "Elena Stone", 35, "Art dealer", "Family friend",
            "Made two private offers for the diamond in the last year, both refused.",
            20, ["Elena's evening dress"],
            [st("location_2230", "dining_hall", "Where were you at 10:30 PM?",
                "Talking to the Hallorans by the window. Ask them, they never stop talking."),
             st("last_saw", "before_dinner", "When did you last see the diamond?",
                "At eight, with everyone else. I have seen it a hundred times.")]),
    ],
    [
        loc("exhibition", "Exhibition Room", "[D]",
            "The display case stands open. There is no broken glass and no mark on the lock.",
            [search("case", "Examine the display case", ["e03"],
                    "The lid is undamaged. Whoever opened this was invited to."),
             search("floor", "Search the floor", ["e01", "e04"],
                    "You go over the carpet on your hands and knees."),
             search("panel", "Inspect the access panel", ["e08"],
                    "The keypad is clean. Too clean, in fact."),
             search("furniture", "Search the nearby furniture", ["e02"],
                    "Behind the console table, dust and one clear print.")]),
        loc("security", "Security Room", "[S]",
            "Six monitors, one of them showing a grey rectangle where the corridor should be.",
            [search("logs", "Pull the camera logs", ["e05"], "The outage is neatly bracketed."),
             search("firmware", "Check the system maintenance record", ["e06"],
                    "A scheduled task, months old, buried in the maintenance list.")]),
        loc("dining", "Dining Hall", "[H]",
            "Forty covers, half-finished wine, and nobody willing to say who left the room.",
            [search("guests", "Speak to the guests", ["e07"],
                    "One of the waiting staff remembers more than the guests do.")]),
        loc("corridor", "Guest Corridor", "[C]",
            "The connecting passage between the dining hall and the exhibition wing.",
            [search("runner", "Examine the carpet runner", ["e09"],
                    "A thread of grey wool caught on the brass stair rod.")]),
        loc("entrance", "Main Entrance", "[E]",
            "The front of the house, where the caterers came and went all evening.",
            [search("register", "Check the arrivals register", ["e10"],
                    "Everyone signed in. Nobody signed out early.")]),
    ],
    [
        ev("e01", "Broken silver button", "A small silver button, torn rather than dropped, found beside the display.",
           "PHYSICAL", 92, 25, "sophia", matches=["Sophia's grey coat"]),
        ev("e02", "Partial fingerprint", "A partial print lifted from the underside of the console table.",
           "PHYSICAL", 88, 20, "sophia"),
        ev("e03", "Undamaged case lock", "The display lock was opened with the correct code, not forced.",
           "PHYSICAL", 100, 10),
        ev("e04", "Grey wool fibre", "A short grey fibre on the carpet directly under the case.",
           "PHYSICAL", 75, 15, "sophia", matches=["Sophia's grey coat"]),
        ev("e05", "Camera outage log", "The corridor camera stopped recording at 10:24 PM.",
           "DIGITAL", 100, 15, "marcus", rh=True, cleared_by="e06"),
        ev("e06", "Firmware restart record", "The outage was an automated firmware restart scheduled in March.",
           "DOCUMENT", 100, 0),
        ev("e07", "Waiter's statement", "A waiter saw Sophia leave the dining hall shortly after ten twenty.",
           "TESTIMONY", 72, 20, "sophia"),
        ev("e08", "Panel access record", "The panel was opened at 10:31 PM using Mr Blackwood's stored code.",
           "DIGITAL", 100, 25, "sophia"),
        ev("e09", "Thread on the stair rod", "Grey wool snagged on brass, at coat height, in the corridor.",
           "PHYSICAL", 80, 10, "sophia"),
        ev("e10", "Adrian's debt notice", "A final demand addressed to Adrian, dated three weeks ago.",
           "DOCUMENT", 85, 12, "adrian", rh=True, cleared_by="e08"),
        ev("e11", "Insurance file annotation", "Sophia's handwriting appears beside the stored panel code in the insurance file.",
           "DOCUMENT", 95, 30, "sophia", requires=["e08", "e07"]),
    ],
    [
        tl("10:00 PM", "The party moves through to dinner."),
        tl("10:15 PM", "The diamond is confirmed in the display."),
        tl("10:22 PM", "Adrian enters the dining hall."),
        tl("10:24 PM", "The exhibition corridor camera stops recording."),
        tl("10:27 PM", "Sophia is seen leaving the dining hall.", True, "e07"),
        tl("10:31 PM", "The exhibition access panel is opened.", True, "e08"),
        tl("10:34 PM", "Marcus attempts to restart the camera."),
        tl("10:36 PM", "Sophia returns to the dining area.", True, "e07"),
        tl("10:45 PM", "The diamond is reported missing."),
    ],
    ["Compare the statements against the timeline between 10:20 and 10:35.",
     "The camera outage may not have been caused by a person at all.",
     "Somebody wrote the panel code down. Find out who read that file."],
))

# ---------------------------------------------------------------- 002
CASES.append(case(
    2, "The Midnight Server Breach", "Valid credentials, an invalid person",
    "Hard", "ethan",
    "NexaCore Technologies", "Data theft", "11:29 PM - 11:48 PM",
    "NexaCore is a fortnight from a confidential product release. At 11:42 PM an "
    "internal monitor records a protected source archive being copied off a "
    "restricted development server. Nobody broke in. Valid employee credentials were "
    "used, a badge belonging to someone at home opened a side door, and a camera "
    "stopped recording for nineteen minutes.",
    "Ethan Blake's contractor account should have been revoked when his engagement "
    "ended. It was not. He borrowed Olivia's badge from the coat rack during his exit "
    "interview, entered through the side door, worked from Maya's unlocked "
    "workstation, and used Ryan's administrator credentials which he had watched "
    "being typed weeks earlier. The camera outage was Daniel's routine firmware push, "
    "and it simply happened to overlap.",
    {"whereabouts": "their whereabouts that night", "credentials": "who could use the admin account",
     "badge": "the badge used at the side door"},
    [
        sus("ryan", "Ryan Cole", 38, "System administrator", "Owns the credentials that were used",
            "Full access to every system that was touched.",
            60, ["Ryan's laptop"],
            [st("whereabouts", "home", "Where were you that night?",
                "At home. My badge never touched the building after six, and you can check that."),
             st("credentials", "stolen", "Your account did this. Explain that.",
                "Then somebody has my password. I have been saying so since the alert came in."),
             st("badge", "unknown", "Whose badge opened the side door?",
                "Not mine. Mine is in the log at 5:52 PM, going out.")]),
        sus("maya", "Maya Chen", 29, "Software engineer", "Her workstation was used",
            "Direct access to the development repositories.",
            30, ["Maya's access card", "Maya's desk drawer"],
            [st("whereabouts", "home", "Where were you that night?",
                "I left at quarter past eight. My partner will tell you when I got in."),
             st("credentials", "not_mine", "Your machine issued the commands.",
                "My machine was on. I do not lock it. That is a bad habit, not a crime."),
             st("badge", "unknown", "Whose badge opened the side door?",
                "I have no idea. Mine is on my keyring and my keyring was with me.")]),
        sus("daniel", "Daniel Ross", 45, "Security officer", "On duty during the outage",
            "Controls the building's cameras and door system.",
            50, ["Daniel's radio"],
            [st("whereabouts", "patrol", "Where were you that night?",
                "On the external patrol, as logged, every twenty minutes."),
             st("credentials", "no_access", "Could you have used the admin account?",
                "I can open doors. I cannot open a repository. Ask anyone."),
             st("badge", "olivia", "Whose badge opened the side door?",
                "The system says Olivia Grant. I flagged it at the time and nobody called me back.")]),
        sus("olivia", "Olivia Grant", 34, "Product manager", "Her badge was used at 11:31 PM",
            "Holds the confidential project documents that were taken.",
            20, ["Olivia's badge", "Olivia's coat"],
            [st("whereabouts", "home", "Where were you that night?",
                "At home from seven. My badge was in my coat pocket in the third floor cloakroom."),
             st("badge", "mine_but_not_me", "Your badge opened the side door.",
                "Then somebody took it out of my coat. I noticed it missing the next morning."),
             st("credentials", "no_access", "Could you have used the admin account?",
                "I cannot deploy a change without three approvals. I certainly cannot do this.")]),
        sus("ethan", "Ethan Blake", 27, "Contract developer", "Engagement ended two days earlier",
            "His access was never revoked and his contract was terminated early.",
            70, ["Ethan's rucksack", "Ethan's USB device"],
            [st("whereabouts", "home", "Where were you that night?",
                "At home. I do not even have a badge any more, so what would I be doing there?", None, True),
             st("credentials", "no_access", "Could you have used the admin account?",
                "My account was disabled on Friday. Whatever this is, it is not me.", None, True),
             st("badge", "unknown", "Whose badge opened the side door?",
                "How would I know? I was let go. I am not on your systems."),
             st("usb", "denied", "A USB device registered to you was connected.",
                "I returned all my equipment. If something has my name on it, someone else kept it.", "e08")]),
    ],
    [
        loc("workstation", "Development Workstation", "[W]",
            "Maya's desk. The screen is still awake and the chair has been moved.",
            [search("session", "Review the session history", ["e01"], "Commands typed by someone who did not know the layout."),
             search("ports", "Check the physical ports", ["e04"], "A USB port with fresh scratches around it.")]),
        loc("server", "Server Room", "[V]",
            "Cold, loud, and very well documented.",
            [search("archive", "Trace the archive access", ["e02"], "The copy took four minutes and thirty seconds."),
             search("deleted", "Recover deleted temporary files", ["e07"], "Someone tidied up, but not thoroughly.")]),
        loc("securityroom", "Security Control Room", "[S]",
            "A wall of feeds, one of which is a grey rectangle for nineteen minutes.",
            [search("camera", "Pull the camera outage record", ["e05"], "11:29 to 11:48. Neat."),
             search("push", "Check the maintenance schedule", ["e06"], "A firmware push, scheduled a fortnight ago.")]),
        loc("entrance", "Building Entrance", "[E]",
            "Two doors: the main lobby, and the side door nobody uses after eight.",
            [search("badge", "Check the badge reader log", ["e03"], "One entry at 11:31 PM."),
             search("cloakroom", "Search the third floor cloakroom", ["e09"], "A coat, a pocket, and no badge in it.")]),
        loc("storage", "Backup Storage Area", "[B]",
            "Shelves of drives, and a signing-out book nobody has enforced in years.",
            [search("register", "Read the equipment register", ["e08"], "Serial NX-8831 was never signed back in."),
             search("accounts", "Audit the account status list", ["e10"], "One contractor account, still partly alive.")]),
        loc("logterminal", "Access Log Terminal", "[L]",
            "The read-only terminal where the building's records can be cross-checked.",
            [search("crossref", "Cross-reference badge and login times", ["e11"], "Two records that cannot both be innocent.")]),
    ],
    [
        ev("e01", "Session history", "Commands run from Maya's workstation at 11:36 PM by someone unfamiliar with the layout.",
           "DIGITAL", 95, 15, "maya", rh=True, cleared_by="e11"),
        ev("e02", "Archive access record", "The protected archive was read at 11:42 PM under Ryan's administrator account.",
           "DIGITAL", 100, 15, "ryan", rh=True, cleared_by="e11"),
        ev("e03", "Side door badge entry", "Olivia Grant's badge opened the side door at 11:31 PM.",
           "DIGITAL", 100, 12, "olivia", rh=True, cleared_by="e09"),
        ev("e04", "USB connection record", "A USB mass storage device was connected at 11:44 PM.",
           "DIGITAL", 98, 18, "ethan"),
        ev("e05", "Camera outage window", "The server corridor camera recorded nothing between 11:29 and 11:48 PM.",
           "DIGITAL", 100, 14, "daniel", rh=True, cleared_by="e06"),
        ev("e06", "Firmware push schedule", "The outage matches a firmware push scheduled two weeks in advance.",
           "DOCUMENT", 100, 0),
        ev("e07", "Deleted temporary archive", "A partially overwritten copy of the archive in the server's temp space.",
           "DIGITAL", 90, 10),
        ev("e08", "Equipment register entry", "USB device NX-8831 is signed out to Ethan Blake and never returned.",
           "DOCUMENT", 96, 30, "ethan"),
        ev("e09", "Empty coat pocket", "Olivia's coat is in the cloakroom. The badge pocket is empty and the lining is pulled.",
           "PHYSICAL", 82, 0),
        ev("e10", "Live contractor account", "Ethan Blake's account was flagged for revocation but remains partly active.",
           "DOCUMENT", 100, 25, "ethan"),
        ev("e11", "Badge and login mismatch", "Ryan's credentials were used while Ryan's badge was outside the building.",
           "DIGITAL", 100, 20, "ethan", requires=["e02", "e03"]),
        ev("e12", "Exit interview record", "Ethan's exit interview was held on the third floor, beside the cloakroom.",
           "DOCUMENT", 94, 28, "ethan", requires=["e09", "e10"]),
    ],
    [
        tl("08:15 PM", "Maya leaves the office."),
        tl("09:03 PM", "A disabled contractor account attempts to authenticate.", True, "e10"),
        tl("10:51 PM", "Ryan receives an automated suspicious-login alert."),
        tl("11:29 PM", "The server corridor camera stops recording."),
        tl("11:31 PM", "A badge opens the side entrance.", True, "e03"),
        tl("11:36 PM", "Maya's workstation becomes active.", True, "e01"),
        tl("11:38 PM", "Administrator credentials are used."),
        tl("11:42 PM", "The confidential archive is accessed.", True, "e02"),
        tl("11:44 PM", "A USB device is connected.", True, "e04"),
        tl("11:47 PM", "Temporary files are deleted.", True, "e07"),
        tl("11:48 PM", "The camera resumes recording."),
    ],
    ["An account is not a person. Ask who could physically be at the keyboard.",
     "Three people look guilty because their property was used. Find who had access to all three.",
     "The cloakroom is on the same floor as the room used for exit interviews."],
))

# ---------------------------------------------------------------- 003
CASES.append(case(
    3, "The Poisoned Professor", "A departmental meeting, and one cup that mattered",
    "Expert", "vikram",
    "Halloway University, Department of Chemistry", "Poisoning", "2:40 PM - 3:20 PM",
    "Professor Alan Reeve collapses forty minutes after a departmental meeting and is "
    "taken to hospital in a critical condition. Toxicology finds a cardiac drug in his "
    "system at several times the therapeutic dose. He does not take that drug. Six "
    "people were in the room, the coffee was poured from a shared pot, and the cups "
    "were laid out in advance with names on them.",
    "Vikram Rao had access to the departmental drug cabinet as the departmental safety "
    "officer, and had learned that Reeve intended to name him in a research misconduct "
    "report the following week. He dosed the cup laid out at Reeve's place before the "
    "meeting began. The medication bottle found in Reeve's office was his own "
    "prescription and had nothing to do with it.",
    {"before_meeting": "where they were before the meeting", "cups": "who laid out the cups",
     "cabinet": "access to the drug cabinet", "report": "the misconduct report"},
    [
        sus("vikram", "Dr Vikram Rao", 44, "Senior lecturer", "Departmental safety officer",
            "Was about to be named in a research misconduct report.",
            25, ["Vikram's lab coat", "Vikram's briefcase"],
            [st("before_meeting", "office", "Where were you before the meeting?",
                "In my office, marking. I came in at two thirty-five with everyone else.", None, True),
             st("cups", "admin", "Who laid the cups out?",
                "The department secretary, as always. It is not a task any of us would want."),
             st("cabinet", "shared", "Who has access to the drug cabinet?",
                "It is a shared key. Half the department could sign it out.", None, True),
             st("report", "unaware", "Were you aware of a misconduct report?",
                "This is the first I have heard of any report.", "e09", True)]),
        sus("helen", "Dr Helen Vance", 51, "Reader", "Chaired the meeting",
            "Competing with Reeve for the same research funding.",
            30, ["Helen's satchel"],
            [st("before_meeting", "seminar_room", "Where were you before the meeting?",
                "Setting up the room from about two twenty. I was in and out."),
             st("cups", "admin", "Who laid the cups out?",
                "Priya did, before I got there. They were already on the side table."),
             st("cabinet", "no", "Do you have drug cabinet access?",
                "No. I have not signed that key out in four years."),
             st("report", "aware", "Were you aware of a misconduct report?",
                "Alan mentioned he was preparing something. He did not say against whom.")]),
        sus("priya", "Priya Raman", 26, "Departmental administrator", "Laid out the room",
            "Was passed over for a permanent contract that Reeve blocked.",
            35, ["Priya's cardigan"],
            [st("before_meeting", "seminar_room", "Where were you before the meeting?",
                "In the seminar room from two fifteen, laying out the cups and the agenda."),
             st("cups", "me", "Who laid the cups out?",
                "I did. Names on the saucers, the way Professor Reeve insists."),
             st("cabinet", "no", "Do you have drug cabinet access?",
                "Absolutely not. I would not know where it is kept."),
             st("report", "unaware", "Were you aware of a misconduct report?",
                "No, and I would have typed it if there were one.")]),
        sus("callum", "Dr Callum Bright", 39, "Lecturer", "Sat beside Reeve",
            "Reeve rejected his promotion case twice.",
            30, ["Callum's jacket"],
            [st("before_meeting", "corridor", "Where were you before the meeting?",
                "In the corridor on the phone until about two thirty-eight."),
             st("cups", "admin", "Who laid the cups out?",
                "Priya. She always does."),
             st("cabinet", "yes", "Do you have drug cabinet access?",
                "I have signed the key out, yes. For a third year practical, in October."),
             st("report", "aware", "Were you aware of a misconduct report?",
                "Everyone knew he was writing one. Nobody knew who it named.")]),
        sus("nadia", "Dr Nadia Okafor", 33, "Postdoctoral researcher", "Took the minutes",
            "Her contract depended on Reeve's grant renewal.",
            15, ["Nadia's notebook"],
            [st("before_meeting", "lab", "Where were you before the meeting?",
                "In the lab until two thirty-six. The instrument log will show it."),
             st("cups", "admin", "Who laid the cups out?",
                "Priya. I saw her carrying the tray in."),
             st("cabinet", "no", "Do you have drug cabinet access?",
                "No. Postdocs are not on that list."),
             st("report", "aware", "Were you aware of a misconduct report?",
                "Alan asked me to check a dataset for him last month. He was very careful about who saw it.")]),
    ],
    [
        loc("seminar", "Seminar Room", "[R]",
            "Twelve chairs, a side table with six cups, and a window that does not open.",
            [search("cup", "Examine Professor Reeve's cup", ["e01"], "A faint residue at the base, below the coffee line."),
             search("pot", "Test the coffee pot", ["e02"], "Clean. Whatever it was, it was not in the pot."),
             search("saucers", "Check the named saucers", ["e03"], "Handwritten cards, one per place.")]),
        loc("office", "Reeve's Office", "[O]",
            "Books to the ceiling and a desk that has not been tidied in a decade.",
            [search("bottle", "Examine the medication bottle", ["e04"], "A prescription in his own name."),
             search("desk", "Search the desk", ["e09"], "A draft document, printed, unsigned."),
             search("bin", "Go through the waste bin", ["e10"], "A torn envelope with a departmental frank.")]),
        loc("cabinet", "Drug Cabinet Store", "[K]",
            "A locked steel cabinet, a signing-out book, and a key nobody guards properly.",
            [search("register", "Read the signing-out register", ["e05"], "One entry the week before, in a hurried hand."),
             search("stock", "Count the stock", ["e06"], "The count is short by more than the register admits.")]),
        loc("lab", "Teaching Laboratory", "[L]",
            "Benches, an instrument log, and a swipe reader on the door.",
            [search("swipes", "Pull the door swipe records", ["e07"], "Everyone's movements, to the minute."),
             search("gloves", "Check the glove bin", ["e08"], "A pair of gloves pushed to the bottom, inside out.")]),
        loc("cafeteria", "Cafeteria", "[C]",
            "Where four of the six were seen at various points that afternoon.",
            [search("till", "Check the till receipts", ["e11"], "Times, to the second, and no ambiguity.")]),
    ],
    [
        ev("e01", "Residue in the cup", "A cardiac drug residue at the base of the cup laid at Reeve's place.",
           "PHYSICAL", 100, 10),
        ev("e02", "Clean coffee pot", "The shared pot tests clear. The dose went into one cup only.",
           "PHYSICAL", 100, 8),
        ev("e03", "Named place cards", "Cups were laid at named places, so the target was chosen in advance.",
           "PHYSICAL", 95, 6),
        ev("e04", "Medication bottle", "A bottle of Reeve's own prescription, unrelated to the drug found.",
           "DOCUMENT", 90, 15, "helen", rh=True, cleared_by="e01"),
        ev("e05", "Cabinet register entry", "The cabinet key was signed out the previous week by V. Rao.",
           "DOCUMENT", 96, 25, "vikram"),
        ev("e06", "Short stock count", "The cabinet holds less of the drug than the register accounts for.",
           "PHYSICAL", 92, 20, "vikram"),
        ev("e07", "Door swipe records", "Vikram entered the seminar room at 2:21 PM, fourteen minutes before he claims.",
           "DIGITAL", 100, 30, "vikram"),
        ev("e08", "Discarded gloves", "A pair of gloves in the lab bin, inside out, with cabinet dust on them.",
           "PHYSICAL", 78, 18, "vikram"),
        ev("e09", "Draft misconduct report", "An unsigned draft naming a senior member of the department.",
           "DOCUMENT", 88, 12),
        ev("e10", "Torn internal envelope", "A departmental envelope addressed to Dr V. Rao, opened and discarded.",
           "DOCUMENT", 85, 22, "vikram"),
        ev("e11", "Cafeteria receipt", "Priya was at the till at 2:19 PM, before the room was laid out.",
           "DOCUMENT", 94, 10, "priya", rh=True, cleared_by="e07"),
        ev("e12", "Named page of the report", "The draft's second page names Vikram Rao directly.",
           "DOCUMENT", 97, 35, "vikram", requires=["e09", "e10"]),
    ],
    [
        tl("02:15 PM", "Priya begins laying out the seminar room."),
        tl("02:19 PM", "Priya is recorded at the cafeteria till.", True, "e11"),
        tl("02:21 PM", "A swipe records entry to the seminar room.", True, "e07"),
        tl("02:35 PM", "Attendees arrive for the meeting."),
        tl("02:40 PM", "The meeting begins. Coffee is poured."),
        tl("03:05 PM", "The meeting ends."),
        tl("03:20 PM", "Professor Reeve collapses in the corridor."),
        tl("03:26 PM", "An ambulance is called."),
    ],
    ["The pot is clean. Ask what that tells you about when the dose was added.",
     "One person's account of their own arrival time can be checked against a door reader.",
     "Find out who the report was going to name."],
))

# ---------------------------------------------------------------- 004
CASES.append(case(
    4, "Murder at the Rosewood Hotel", "Room 707, locked from the inside",
    "Hard", "irene",
    "The Rosewood Hotel, Room 707", "Murder", "1:10 AM - 2:05 AM",
    "Gerald Payne, a property developer, is found dead in room 707 at seven in the "
    "morning. The door is bolted from the inside and the window is sealed. The night "
    "manager opened it with the master key after Payne missed a car to the airport. "
    "There is one wine glass on the table where the room service docket says there "
    "should be two.",
    "Irene Falk was in the room as Payne's guest. She left through the connecting door "
    "to room 705, which she had booked under her maiden name, and bolted 707 from the "
    "inside by reaching through that connecting door before closing it. The missing "
    "second glass was in her own room. The elevator record that seemed to clear her "
    "only shows the main lift, not the service stair.",
    {"night_of": "where they were that night", "glass": "the missing second glass",
     "connecting": "the connecting door", "leaving": "when they left the hotel"},
    [
        sus("irene", "Irene Falk", 41, "Investor", "Business partner of the victim",
            "Stood to lose everything in the partnership dissolution Payne had filed.",
            25, ["Irene's silk scarf", "Irene's room key"],
            [st("night_of", "own_room", "Where were you that night?",
                "In my own room from about midnight. I took the lift up at 11:50.", None, True),
             st("glass", "unknown", "There should be two glasses. Where is the second?",
                "How would I know? Perhaps housekeeping took it.", None, True),
             st("connecting", "locked", "Was the connecting door to 705 in use?",
                "It was locked. Those doors are always locked.", "e05", True),
             st("leaving", "morning", "When did you leave the hotel?",
                "At seven, like everyone else. I heard the commotion in the corridor.")]),
        sus("marcus_h", "Marcus Hale", 55, "Night manager", "Found the body",
            "Payne had complained about him twice and wanted him dismissed.",
            40, ["Marcus's master key"],
            [st("night_of", "front_desk", "Where were you that night?",
                "At the desk. I did a floor check at one and again at three."),
             st("glass", "unknown", "There should be two glasses. Where is the second?",
                "The docket says two. I signed it myself. I cannot tell you where it went."),
             st("connecting", "unknown", "Was the connecting door to 705 in use?",
                "705 was occupied. I would have to check under what name."),
             st("leaving", "shift_end", "When did you leave the hotel?",
                "Seven fifteen, after the police arrived.")]),
        sus("dominic", "Dominic Vance", 33, "Room service attendant", "Delivered the wine",
            "Payne had him disciplined for an earlier complaint.",
            30, ["Dominic's service jacket"],
            [st("night_of", "service_floor", "Where were you that night?",
                "On the service floor. I took the order up at ten past one and came straight down."),
             st("glass", "two", "There should be two glasses. Where is the second?",
                "There were two on the tray. I set them both out. Somebody else moved one."),
             st("connecting", "open", "Was the connecting door to 705 in use?",
                "It was ajar when I came in. I remember because it was odd.", "e04"),
             st("leaving", "shift_end", "When did you leave the hotel?",
                "Six in the morning, end of shift.")]),
        sus("harriet", "Harriet Payne", 48, "The victim's sister", "Staying on the fifth floor",
            "Inherits the controlling share of the family business.",
            35, ["Harriet's overcoat"],
            [st("night_of", "own_room", "Where were you that night?",
                "In 512. I took a sleeping tablet at eleven and heard nothing."),
             st("glass", "unknown", "There should be two glasses. Where is the second?",
                "I was not in his room. I had not spoken to Gerald in a fortnight."),
             st("leaving", "morning", "When did you leave the hotel?",
                "I have not left. I am still here, being asked questions.")]),
    ],
    [
        loc("room707", "Room 707", "[7]",
            "Bolted from within. One glass, one chair pulled out, and a connecting door in the east wall.",
            [search("table", "Examine the table", ["e01"], "One glass, and a ring of condensation where a second stood."),
             search("bolt", "Examine the door bolt", ["e02"], "Thrown from inside, with a scuff on the plate."),
             search("connecting", "Try the connecting door", ["e04"], "It gives. It is not locked."),
             search("floor", "Search the floor", ["e03"], "A thread of pale silk caught in the connecting hinge.")]),
        loc("room705", "Room 705", "[5]",
            "Booked, paid for, and apparently unslept in.",
            [search("register", "Check the booking name", ["e05"], "A maiden name, and a card that matches another guest."),
             search("bin705", "Search the room", ["e06"], "A second wine glass, rinsed but not dried.")]),
        loc("lobby", "Lobby and Front Desk", "[L]",
            "Where the night manager sat and the lift record was kept.",
            [search("lift", "Pull the elevator record", ["e07"], "Irene up at 11:50 PM, and nothing after."),
             search("docket", "Find the room service docket", ["e08"], "One bottle, two glasses, signed at 1:10 AM.")]),
        loc("service", "Service Stair", "[S]",
            "The staff stair between floors, uncovered by the guest lift log.",
            [search("stairdoor", "Check the stair door counter", ["e09"], "A mechanical counter, and one use at 1:42 AM."),
             search("stairfloor", "Search the stair landing", ["e10"], "Nothing but dust, and one clean footprint in it.")]),
        loc("fifth", "Fifth Floor Corridor", "[F]",
            "Harriet's floor, and the corridor camera that covers it.",
            [search("camera5", "Review the corridor camera", ["e11"], "Nobody leaves 512 between eleven and seven.")]),
    ],
    [
        ev("e01", "Single wine glass", "One glass on the table, with a condensation ring where a second stood.",
           "PHYSICAL", 100, 8),
        ev("e02", "Bolt thrown from inside", "The bolt was thrown from within, with a scuff mark on the strike plate.",
           "PHYSICAL", 98, 6),
        ev("e03", "Pale silk thread", "A pale silk fibre caught in the hinge of the connecting door.",
           "PHYSICAL", 84, 22, "irene", matches=["Irene's silk scarf"]),
        ev("e04", "Unlocked connecting door", "The connecting door between 707 and 705 is not locked.",
           "PHYSICAL", 100, 15, "irene"),
        ev("e05", "Booking under a maiden name", "Room 705 is booked to I. Marsh, paid with Irene Falk's card.",
           "DOCUMENT", 96, 28, "irene"),
        ev("e06", "The second glass", "A rinsed wine glass in room 705, matching the set from 707.",
           "PHYSICAL", 92, 26, "irene"),
        ev("e07", "Elevator record", "Irene took the guest lift up at 11:50 PM and is not recorded coming down.",
           "DIGITAL", 100, 10, "marcus_h", rh=True, cleared_by="e09"),
        ev("e08", "Room service docket", "One bottle and two glasses delivered to 707 at 1:10 AM.",
           "DOCUMENT", 100, 12, "dominic", rh=True, cleared_by="e06"),
        ev("e09", "Service stair counter", "The stair door counter records one use at 1:42 AM.",
           "PHYSICAL", 88, 14),
        ev("e10", "Footprint on the landing", "A single clean print in the dust of the service landing.",
           "PHYSICAL", 76, 12, "irene"),
        ev("e11", "Fifth floor camera", "Nobody leaves room 512 between 11 PM and 7 AM.",
           "DIGITAL", 100, 0),
        ev("e12", "Partnership dissolution filing", "Payne had filed to dissolve the partnership, leaving Falk exposed.",
           "DOCUMENT", 95, 30, "irene", requires=["e05", "e06"]),
    ],
    [
        tl("11:50 PM", "Irene takes the guest lift to the seventh floor."),
        tl("01:10 AM", "Room service delivers one bottle and two glasses to 707."),
        tl("01:14 AM", "The service attendant leaves the floor."),
        tl("01:42 AM", "The service stair door is used once.", True, "e09"),
        tl("01:55 AM", "The connecting door between 707 and 705 is closed.", True, "e04"),
        tl("02:05 AM", "The bolt on 707 is thrown.", True, "e02"),
        tl("03:00 AM", "The night manager completes a floor check."),
        tl("07:00 AM", "Room 707 is opened with the master key."),
    ],
    ["A room bolted from inside is only impossible if there is one way in.",
     "The docket says two glasses. Find the second one.",
     "The guest lift is not the only way between floors."],
))

# ---------------------------------------------------------------- 005
CASES.append(case(
    5, "The Vanishing Programmer", "Missing, one day before release",
    "Hard", "leon",
    "Arclight Systems", "Disappearance", "6:40 PM - 11:00 PM",
    "Sana Iqbal, lead engineer on a confidential machine learning product, does not "
    "arrive for the release rehearsal. Her car is in the company car park, her pass is "
    "in her desk drawer, and her phone last connected to the office network at 6:40 PM "
    "the previous evening. Her manager reports her missing. The board wants it treated "
    "as industrial espionage.",
    "Sana was not taken. She left deliberately, after discovering that Leon Marsh had "
    "been falsifying the model's evaluation figures for eighteen months. She copied "
    "the evidence, drove a hire car to her sister's, and left her own car and pass "
    "behind so that nobody would look for a vehicle. Leon reported her missing loudly "
    "and early, hoping the espionage story would land before she surfaced.",
    {"last_seen": "when they last saw Sana", "repository": "the repository activity",
     "evaluation": "the evaluation figures"},
    [
        sus("leon", "Leon Marsh", 47, "Head of research", "Sana's manager",
            "Sana had found eighteen months of falsified evaluation results.",
            30, ["Leon's office key", "Leon's laptop"],
            [st("last_seen", "six_thirty", "When did you last see Sana?",
                "About half past six. She said she was going to finish the eval report."),
             st("repository", "normal", "Was there unusual repository activity?",
                "Nothing beyond the usual pre-release churn.", None, True),
             st("evaluation", "clean", "Are the evaluation figures sound?",
                "They have been reviewed three times. They are sound.", "e06", True)]),
        sus("dev", "Dev Anand", 31, "Platform engineer", "Sat opposite Sana",
            "Was passed over for the lead role that went to Sana.",
            35, ["Dev's rucksack"],
            [st("last_seen", "six_forty", "When did you last see Sana?",
                "Twenty to seven. She was printing something and she looked ill."),
             st("repository", "unusual", "Was there unusual repository activity?",
                "She pulled the whole eval history at half six. That is not normal."),
             st("evaluation", "suspect", "Are the evaluation figures sound?",
                "I have never been allowed to see the raw runs. Make of that what you like.")]),
        sus("marta", "Marta Kovac", 38, "Security lead", "Runs the building access system",
            "Deleted a block of camera footage the same evening.",
            45, ["Marta's tablet"],
            [st("last_seen", "not_seen", "When did you last see Sana?",
                "I did not see her that day at all."),
             st("repository", "not_my_area", "Was there unusual repository activity?",
                "Not my system. I watch doors, not branches."),
             st("footage", "retention", "Why was the car park footage deleted?",
                "Thirty day retention, automatically. It ran the night she vanished. Bad luck.", "e04")]),
        sus("bea", "Bea Nolan", 29, "Product manager", "Coordinating the release",
            "Her bonus depended on shipping on time.",
            25, ["Bea's planner"],
            [st("last_seen", "six_fifteen", "When did you last see Sana?",
                "Quarter past six, in the kitchen. She asked me what happens if a release is pulled."),
             st("repository", "unusual", "Was there unusual repository activity?",
                "I do not read commits. But she asked me about pulling the release, which was new."),
             st("evaluation", "suspect", "Are the evaluation figures sound?",
                "Sana raised a concern in writing last month. It was marked as resolved by Leon.")]),
    ],
    [
        loc("desk", "Sana's Desk", "[D]",
            "Two monitors, a cold cup of tea, and a pass sitting squarely in an open drawer.",
            [search("drawer", "Search the drawer", ["e01"], "The pass, placed deliberately, not dropped."),
             search("machine", "Examine her workstation", ["e02"], "A shell history that reads like a plan."),
             search("printer", "Check the printer queue", ["e03"], "One job, 62 pages, collected.")]),
        loc("carpark", "Car Park", "[P]",
            "Her car in bay 41, cold, locked, and covered in a night's dust.",
            [search("car", "Examine her car", ["e05"], "Nothing disturbed. It has not been driven."),
             search("cctv", "Request the car park footage", ["e04"], "The relevant night is gone.")]),
        loc("repo", "Repository Server", "[R]",
            "Where the eighteen months of history live.",
            [search("history", "Trace the repository access", ["e06"], "She pulled everything, then stopped."),
             search("blame", "Examine the evaluation commits", ["e07"], "One account rewrote the same numbers eleven times.")]),
        loc("mail", "Mail Archive", "[M]",
            "The retained copy of everything anyone sent.",
            [search("thread", "Search Sana's outbound mail", ["e08"], "A concern raised, and an answer that closes it."),
             search("leonmail", "Search Leon's outbound mail", ["e09"], "A note sent at 7:02 PM that should not exist yet.")]),
        loc("gate", "Site Gate", "[G]",
            "One barrier, one camera, and a log of every plate that passes.",
            [search("plates", "Read the plate register", ["e10"], "A hire car in at 6:20 PM and out at 6:58 PM.")]),
    ],
    [
        ev("e01", "Abandoned pass", "Her access pass was placed in her drawer, not lost.",
           "PHYSICAL", 96, 6),
        ev("e02", "Shell history", "A sequence of commands ending in a full export of the evaluation history.",
           "DIGITAL", 98, 10),
        ev("e03", "Print job record", "A 62 page document printed at 6:34 PM and collected.",
           "DIGITAL", 94, 8),
        ev("e04", "Deleted car park footage", "The car park recording for that night has been removed.",
           "DIGITAL", 90, 20, "marta", rh=True, cleared_by="e10"),
        ev("e05", "Undisturbed car", "Her car has not been driven and shows no sign of a struggle.",
           "PHYSICAL", 100, 5),
        ev("e06", "Repository export", "Sana pulled the complete evaluation history at 6:31 PM.",
           "DIGITAL", 100, 12),
        ev("e07", "Rewritten evaluation commits", "One account amended the same evaluation figures eleven times.",
           "DIGITAL", 97, 30, "leon"),
        ev("e08", "Sana's raised concern", "A written concern about the figures, marked resolved without a reply.",
           "DOCUMENT", 95, 22, "leon"),
        ev("e09", "Premature missing person note", "Leon reported Sana missing at 7:02 PM, before anyone had missed her.",
           "DOCUMENT", 92, 28, "leon"),
        ev("e10", "Hire car plate record", "A hire car entered at 6:20 PM and left at 6:58 PM with one occupant.",
           "DOCUMENT", 88, 10),
        ev("e11", "Hire agreement", "The hire car was booked in Sana's name, three days in advance.",
           "DOCUMENT", 94, 0, requires=["e10", "e01"]),
        ev("e12", "Amended commit authorship", "The rewritten commits were authored under Leon's signing key.",
           "DIGITAL", 99, 35, "leon", requires=["e07", "e09"]),
    ],
    [
        tl("06:15 PM", "Sana speaks to Bea in the kitchen."),
        tl("06:20 PM", "A hire car enters the site.", True, "e10"),
        tl("06:31 PM", "The full evaluation history is exported.", True, "e06"),
        tl("06:34 PM", "A 62 page document is printed.", True, "e03"),
        tl("06:40 PM", "Sana's phone leaves the office network."),
        tl("06:58 PM", "The hire car leaves the site.", True, "e10"),
        tl("07:02 PM", "Leon files a missing person note.", True, "e09"),
        tl("11:00 PM", "Sana's phone is switched off for the last time."),
    ],
    ["Ask why someone taken against their will would put their pass away neatly.",
     "Somebody reported her missing before anybody knew she was gone.",
     "The evaluation history was rewritten. Find whose key signed it."],
))
