"""Cases 011-015."""

from casekit import case, ev, loc, search, st, sus, tl

CASES = []

# ---------------------------------------------------------------- 011
CASES.append(case(
    11, "The Understudy", "One rope, one cue, one person who knew both",
    "Easy", "gareth",
    "The Lyceum Playhouse", "Attempted murder", "7:40 PM - 8:05 PM",
    "During a preview performance, a counterweight bar falls onto the stage a metre "
    "from the lead actress, Delia Mount. Nobody is hurt. The rigging is inspected and "
    "the securing pin is found on the fly floor, removed rather than sheared. Only "
    "someone who knew the cue sheet would know when Delia stood on that mark.",
    "Gareth Tull, the deputy stage manager, pulled the pin during the interval. He "
    "calls the cues, so he knew to the second where Delia would be standing. His "
    "motive was the understudy, Kirsty, to whom he had promised the part. The frayed "
    "rope that suggested neglect was on a different line entirely, and the missing "
    "maintenance signature was a clerical lapse from two months earlier.",
    {"interval": "where they were during the interval", "cues": "who knows the cue sheet",
     "flyfloor": "access to the fly floor"},
    [
        sus("gareth", "Gareth Tull", 34, "Deputy stage manager", "Calls the show",
            "Promised the lead role to the understudy, whom he is involved with.",
            25, ["Gareth's headset", "Gareth's cue book"],
            [st("interval", "prompt_corner", "Where were you during the interval?",
                "At the prompt corner, marking up act two. I never left it.", None, True),
             st("cues", "several", "Who knows the cue sheet?",
                "Anyone on comms. It is not a secret document."),
             st("flyfloor", "restricted", "Who can reach the fly floor?",
                "Flys and technical staff. It is signed and restricted.", "e04", True)]),
        sus("kirsty", "Kirsty Vale", 26, "Understudy", "Would play the lead",
            "Directly benefits if the lead cannot perform.",
            45, ["Kirsty's dressing gown"],
            [st("interval", "dressing_room", "Where were you during the interval?",
                "In the dressing room with two other people. Ask them."),
             st("cues", "roughly", "Who knows the cue sheet?",
                "I know the blocking. I do not know the technical cues."),
             st("flyfloor", "no_access", "Who can reach the fly floor?",
                "Not performers. I have never been up there.")]),
        sus("harry", "Harry Dunn", 58, "Head flyman", "Operates the rigging",
            "Responsible for the maintenance record that has a gap in it.",
            35, ["Harry's tool belt"],
            [st("interval", "fly_floor", "Where were you during the interval?",
                "On the fly floor, resetting for act two. That is my job."),
             st("cues", "several", "Who knows the cue sheet?",
                "Everyone on comms hears the cues called."),
             st("flyfloor", "restricted", "Who can reach the fly floor?",
                "Restricted, but the door is propped half the night. It should not be.")]),
        sus("delia", "Delia Mount", 41, "Lead actress", "The intended target",
            "Reported a stalker to the theatre a month ago and was not taken seriously.",
            10, ["Delia's costume"],
            [st("interval", "stage_left", "Where were you during the interval?",
                "Stage left, in the wings, going over the second act with the director."),
             st("cues", "roughly", "Who knows the cue sheet?",
                "I know my own marks. That is all any of us know."),
             st("flyfloor", "no_access", "Who can reach the fly floor?",
                "I would not know how to get up there.")]),
    ],
    [
        loc("stage", "The Stage", "[S]",
            "A counterweight bar embedded in the boards, a metre from a chalked mark.",
            [search("bar", "Examine the fallen bar", ["e01"], "Clean release. Nothing sheared."),
             search("mark", "Examine the chalk mark", ["e02"], "Delia's mark for the act two opening.")]),
        loc("flyfloor", "Fly Floor", "[F]",
            "Ropes, weights, and a door that is supposed to be locked.",
            [search("pin", "Search for the securing pin", ["e03"], "On the floor, straight, unbent."),
             search("door", "Check the fly floor door", ["e04"], "Propped open with a fire extinguisher."),
             search("rope", "Inspect the ropes", ["e05"], "One frayed line, on a different bar entirely.")]),
        loc("prompt", "Prompt Corner", "[P]",
            "The desk from which the show is called.",
            [search("cuebook", "Examine the cue book", ["e06"], "Act two annotated in a fresh hand."),
             search("comms", "Pull the comms recording", ["e07"], "Fifty seconds of silence on one channel.")]),
        loc("office", "Stage Door Office", "[O]",
            "The book that records everyone who came and went.",
            [search("signin", "Read the sign-in book", ["e08"], "One name signed in for the interval and not out."),
             search("maint", "Check the maintenance record", ["e09"], "A gap, dated two months ago.")]),
        loc("dressing", "Dressing Rooms", "[D]",
            "Where three people can account for each other, and one cannot.",
            [search("alibis", "Take the interval statements", ["e10"], "Two independent accounts, consistent.")]),
    ],
    [
        ev("e01", "Cleanly released bar", "The counterweight bar released cleanly. Nothing failed.",
           "PHYSICAL", 100, 8),
        ev("e02", "Chalked mark", "The bar fell a metre from the lead's act two opening mark.",
           "PHYSICAL", 95, 10),
        ev("e03", "Removed securing pin", "The pin was withdrawn by hand, not sheared or bent.",
           "PHYSICAL", 97, 18, "gareth"),
        ev("e04", "Propped fly floor door", "The restricted door was propped open throughout the interval.",
           "PHYSICAL", 88, 12),
        ev("e05", "Frayed rope", "A frayed line, on a bar that had nothing to do with the incident.",
           "PHYSICAL", 82, 20, "harry", rh=True, cleared_by="e01"),
        ev("e06", "Annotated cue book", "Act two cues re-marked in fresh ink during the interval.",
           "DOCUMENT", 90, 24, "gareth"),
        ev("e07", "Comms silence", "The deputy stage manager's channel is silent for fifty seconds.",
           "DIGITAL", 93, 26, "gareth"),
        ev("e08", "Sign-in book", "One name signed in for the interval with no corresponding exit.",
           "DOCUMENT", 86, 14, "gareth"),
        ev("e09", "Maintenance gap", "An unsigned maintenance inspection from two months earlier.",
           "DOCUMENT", 84, 16, "harry", rh=True, cleared_by="e03"),
        ev("e10", "Dressing room accounts", "Two independent witnesses place the understudy in the dressing room.",
           "TESTIMONY", 88, 0),
        ev("e11", "Message to the understudy", "A message promising the part, sent an hour before the performance.",
           "DIGITAL", 94, 30, "gareth", requires=["e07", "e06"]),
    ],
    [
        tl("07:40 PM", "The interval begins."),
        tl("07:46 PM", "The fly floor door is propped open.", True, "e04"),
        tl("07:52 PM", "One comms channel goes silent for fifty seconds.", True, "e07"),
        tl("07:58 PM", "The cue book is annotated.", True, "e06"),
        tl("08:00 PM", "The interval ends."),
        tl("08:05 PM", "The counterweight bar falls."),
    ],
    ["The bar did not fail. Somebody released it.",
     "Ask who knew, to the second, where the actress would be standing.",
     "Fifty seconds of silence on a channel that never stops talking."],
))

# ---------------------------------------------------------------- 012
CASES.append(case(
    12, "The Kiln Room", "A fire that started twice",
    "Medium", "marguerite",
    "Halden Ceramics Works", "Arson and insurance fraud", "11:20 PM - 12:40 AM",
    "A fire destroys the glazing shed at a ceramics works. The insurance claim is "
    "substantial and the business was three months from closure. The fire "
    "investigator's report finds two separate points of origin, which rules out an "
    "accident. Four people held keys to the site.",
    "Marguerite Halden set the fire herself to recover the value of a business she "
    "could not sell. She used the kiln's own timer to create a delayed second point of "
    "origin, giving herself a clean alibi at a restaurant eleven miles away. The night "
    "watchman's late arrival and the electrician's unfinished rewiring were both "
    "genuine and both irrelevant.",
    {"that_night": "where they were that night", "keys": "who holds a site key",
     "kiln": "the kiln timer"},
    [
        sus("marguerite", "Marguerite Halden", 57, "Owner", "Runs the works",
            "The business was three months from closure and heavily insured.",
            30, ["Marguerite's key ring", "Marguerite's car"],
            [st("that_night", "restaurant", "Where were you that night?",
                "At the Fern and Anchor from nine until eleven. Eleven miles away."),
             st("keys", "four", "Who holds a site key?",
                "Four of us. Myself, Joe, the electrician, and the kiln technician."),
             st("kiln", "off", "Was the kiln in use?",
                "It was shut down for the weekend. It had been cold since Friday.", "e04", True)]),
        sus("joe", "Joe Merrick", 63, "Night watchman", "Should have been on site",
            "Arrived forty minutes late and did not report it.",
            45, ["Joe's torch"],
            [st("that_night", "late", "Where were you that night?",
                "I was late. Forty minutes. I have never been late in nine years and I am sick about it."),
             st("keys", "four", "Who holds a site key?",
                "Four keys. Mine is on my belt and always has been."),
             st("kiln", "off", "Was the kiln in use?",
                "Cold since Friday. I checked it on my Saturday round.")]),
        sus("electrician", "Sam Iqbal", 41, "Electrician", "Rewiring the glazing shed",
            "The rewiring was unfinished and left exposed connections.",
            35, ["Sam's tool case"],
            [st("that_night", "home", "Where were you that night?",
                "At home from six. My last visit to site was Thursday."),
             st("keys", "four", "Who holds a site key?",
                "I hold one while the job runs. I hand it back at the end."),
             st("kiln", "not_my_area", "Was the kiln in use?",
                "I do not touch the kiln circuits. That is a separate contract.")]),
        sus("technician", "Ruth Okoye", 33, "Kiln technician", "Maintains the kilns",
            "Programmed the kiln controller the week before.",
            30, ["Ruth's service log"],
            [st("that_night", "home", "Where were you that night?",
                "At home. I finished the Friday service at four and left."),
             st("keys", "four", "Who holds a site key?",
                "Four. Mine has not left the works, I keep it in the plant room."),
             st("kiln", "programmed", "Was the kiln in use?",
                "I left a schedule on the controller. It should not have fired without a manual start.")]),
    ],
    [
        loc("shed", "Glazing Shed", "[G]",
            "What is left of it. Two areas of deep charring, ten metres apart.",
            [search("origin1", "Examine the first point of origin", ["e01"], "Near the door, an accelerant pattern."),
             search("origin2", "Examine the second point of origin", ["e02"], "At the kiln wall, and it started later."),
             search("wiring", "Inspect the new wiring", ["e03"], "Unfinished, but isolated at the board.")]),
        loc("kilnroom", "Kiln Room", "[K]",
            "The controller survived. It remembers everything.",
            [search("controller", "Read the kiln controller", ["e04"], "A manual start, programmed for 12:15 AM."),
             search("servicelog", "Read the service log", ["e05"], "Ruth's Friday entry, and one after it.")]),
        loc("gatehouse", "Gatehouse", "[H]",
            "Where the watchman signs on and the barrier records every vehicle.",
            [search("signon", "Check the sign-on record", ["e06"], "Forty minutes late, and honest about it."),
             search("barrier", "Read the barrier log", ["e07"], "One vehicle in at 11:20 PM and out at 11:34 PM.")]),
        loc("office", "Works Office", "[O]",
            "Accounts, correspondence, and an insurance file that has been updated recently.",
            [search("accounts", "Examine the accounts", ["e08"], "Three months of runway, at best."),
             search("insurance", "Read the insurance file", ["e09"], "Cover increased seven weeks ago.")]),
        loc("restaurant", "The Fern and Anchor", "[F]",
            "Eleven miles away, with a card machine that timestamps everything.",
            [search("bill", "Check the bill", ["e10"], "Paid at 10:52 PM, not eleven."),
             search("staffr", "Speak to the staff", ["e11"], "They remember the table leaving early.")]),
    ],
    [
        ev("e01", "First point of origin", "An accelerant pattern near the shed door, ignited first.",
           "PHYSICAL", 100, 10),
        ev("e02", "Delayed second origin", "A second origin at the kiln wall that began roughly an hour later.",
           "PHYSICAL", 97, 14),
        ev("e03", "Unfinished wiring", "The new wiring is incomplete but isolated at the distribution board.",
           "PHYSICAL", 92, 20, "electrician", rh=True, cleared_by="e01"),
        ev("e04", "Kiln controller record", "A manual start was programmed for 12:15 AM.",
           "DIGITAL", 99, 30, "marguerite"),
        ev("e05", "Service log entry", "An entry after the technician's Friday service, in a different hand.",
           "DOCUMENT", 90, 24, "marguerite"),
        ev("e06", "Late sign-on", "The watchman signed on forty minutes late and recorded it himself.",
           "DOCUMENT", 94, 18, "joe", rh=True, cleared_by="e07"),
        ev("e07", "Barrier vehicle log", "A vehicle entered at 11:20 PM and left at 11:34 PM.",
           "DIGITAL", 98, 26, "marguerite"),
        ev("e08", "Accounts position", "The works had three months of runway remaining.",
           "DOCUMENT", 96, 12, "marguerite"),
        ev("e09", "Increased cover", "The insurance cover was increased seven weeks before the fire.",
           "DOCUMENT", 95, 28, "marguerite"),
        ev("e10", "Restaurant bill", "The bill was settled at 10:52 PM, not at eleven.",
           "DOCUMENT", 97, 22, "marguerite"),
        ev("e11", "Restaurant staff account", "Staff recall the table leaving noticeably early.",
           "TESTIMONY", 76, 14, "marguerite"),
        ev("e12", "Vehicle identification", "The barrier record identifies the owner's car.",
           "DIGITAL", 96, 32, "marguerite", requires=["e07", "e10"]),
    ],
    [
        tl("10:52 PM", "A restaurant bill is settled eleven miles away.", True, "e10"),
        tl("11:20 PM", "A vehicle enters the works.", True, "e07"),
        tl("11:34 PM", "The vehicle leaves the works.", True, "e07"),
        tl("11:40 PM", "The first fire is set near the shed door."),
        tl("12:00 AM", "The night watchman signs on, forty minutes late.", True, "e06"),
        tl("12:15 AM", "The kiln controller executes a programmed start.", True, "e04"),
        tl("12:40 AM", "The fire is reported."),
    ],
    ["Two points of origin means two decisions, not one accident.",
     "One of them started an hour after the other. Ask what could do that on a timer.",
     "Check the alibi's timestamp rather than the alibi's owner."],
))

# ---------------------------------------------------------------- 013
CASES.append(case(
    13, "The Sealed Laboratory", "Nobody entered. The sample is still gone.",
    "Expert", "unit",
    "Vansi Biosciences, Containment Wing", "Theft of controlled material", "3:00 AM - 3:40 AM",
    "A controlled biological sample is removed from a sealed containment laboratory. "
    "The room requires two independent authorisations to open, both of which are "
    "logged, and neither was used that night. The internal camera shows an empty room "
    "for the entire period. The sample is simply present at 3:00 AM and absent at "
    "3:40 AM.",
    "Nobody entered because nobody needed to. Dr Ilse Unterberg had reprogrammed the "
    "automated sample-handling arm three days earlier to move the vial into an "
    "outgoing waste cassette at 3:12 AM. The camera showed an empty room because the "
    "room was empty. She collected the cassette from the loading dock the following "
    "morning through an entirely ordinary process nobody thinks to watch.",
    {"that_night": "where they were that night", "authorisation": "the two-key authorisation",
     "arm": "the sample handling arm"},
    [
        sus("unit", "Dr Ilse Unterberg", 46, "Principal investigator", "Wrote the handling routines",
            "Her funding was terminated and the sample is the basis of her next application.",
            25, ["Ilse's laptop", "Ilse's access token"],
            [st("that_night", "home", "Where were you that night?",
                "At home, asleep. My token has not been used since Tuesday evening."),
             st("authorisation", "unused", "Was the two-key authorisation used?",
                "It was not. That is the point of it. Nobody opened that room."),
             st("arm", "standard", "Was the handling arm operating?",
                "It runs a standard maintenance cycle overnight. It always has.", "e05", True)]),
        sus("safety", "Dr Colin Frayne", 52, "Biosafety officer", "Holds one of the two keys",
            "Signed off a containment exemption for the sample a week earlier.",
            35, ["Colin's key card"],
            [st("that_night", "on_call", "Where were you that night?",
                "On call at home. I was not paged and I did not attend."),
             st("authorisation", "unused", "Was the two-key authorisation used?",
                "No. And it cannot be used singly. That is the whole design."),
             st("arm", "not_my_area", "Was the handling arm operating?",
                "Robotics is not my discipline. I sign for containment, not code.")]),
        sus("tech", "Nuno Ferreira", 31, "Automation technician", "Maintains the handling arm",
            "Pushed a firmware update to the arm the same week.",
            40, ["Nuno's service tablet"],
            [st("that_night", "home", "Where were you that night?",
                "At home. I have not been on site after six for a fortnight."),
             st("authorisation", "unused", "Was the two-key authorisation used?",
                "Not according to the log, and I cannot use it at all."),
             st("arm", "updated", "Was the handling arm operating?",
                "I pushed a firmware update on the Monday. Routine. The routines on it are not mine.")]),
        sus("postdoc", "Dr Yara Haddad", 34, "Postdoctoral researcher", "Uses the room daily",
            "Would be named on the application the sample supports.",
            30, ["Yara's notebook"],
            [st("that_night", "home", "Where were you that night?",
                "At home. I left at seven and my token log will say so."),
             st("authorisation", "unused", "Was the two-key authorisation used?",
                "No. I checked the log myself when I heard."),
             st("arm", "standard", "Was the handling arm operating?",
                "It runs overnight. We all assume it does nothing interesting.")]),
    ],
    [
        loc("containment", "Containment Laboratory", "[C]",
            "Sealed, monitored, and completely empty for the entire period in question.",
            [search("rack", "Examine the sample rack", ["e01"], "One empty position, and no disturbance around it."),
             search("camerac", "Review the internal camera", ["e02"], "Forty minutes of an empty room."),
             search("armlog", "Read the handling arm log", ["e03"], "One movement, at 3:12 AM.")]),
        loc("authroom", "Authorisation Control", "[A]",
            "The two-key system, and a log that has never been wrong.",
            [search("keylog", "Read the authorisation log", ["e04"], "No authorisation on the night in question."),
             search("tokens", "Check the access tokens", ["e09"], "Nobody's token was used after Tuesday.")]),
        loc("robotics", "Robotics Bay", "[R]",
            "Where the arm's routines are written, versioned and signed.",
            [search("routines", "Examine the routine history", ["e05"], "A routine amended three days before."),
             search("firmware", "Check the firmware push", ["e06"], "Routine, versioned, and unrelated to the routines."),
             search("signature", "Check the routine signatures", ["e07"], "One amendment signed by a research account.")]),
        loc("dock", "Loading Dock", "[L]",
            "Where waste cassettes leave the building, watched by nobody in particular.",
            [search("cassette", "Trace the waste cassettes", ["e08"], "One cassette collected by hand, out of sequence."),
             search("dockcam", "Review the dock camera", ["e10"], "A collection at 8:40 AM, entirely ordinary.")]),
        loc("grants", "Grants Office", "[G]",
            "Applications, terminations, and the dates that connect them.",
            [search("funding", "Read the funding record", ["e11"], "One termination, and one application in preparation.")]),
    ],
    [
        ev("e01", "Empty rack position", "The sample position is empty with no sign of disturbance.",
           "PHYSICAL", 100, 6),
        ev("e02", "Empty room footage", "The internal camera shows an empty laboratory throughout.",
           "DIGITAL", 100, 8),
        ev("e03", "Handling arm movement", "The arm executed one movement at 3:12 AM.",
           "DIGITAL", 99, 20, "unit"),
        ev("e04", "Unused authorisation log", "No two-key authorisation was recorded that night.",
           "DIGITAL", 100, 6),
        ev("e05", "Amended routine", "A handling routine was amended three days before the theft.",
           "DIGITAL", 97, 28, "unit"),
        ev("e06", "Firmware push record", "The technician's firmware update is routine and does not touch routines.",
           "DOCUMENT", 96, 22, "tech", rh=True, cleared_by="e07"),
        ev("e07", "Routine signature", "The amendment is signed by the principal investigator's research account.",
           "DIGITAL", 98, 32, "unit"),
        ev("e08", "Out-of-sequence cassette", "One waste cassette was collected by hand, out of the normal sequence.",
           "DOCUMENT", 91, 24, "unit"),
        ev("e09", "Token access record", "No access token was used after Tuesday evening.",
           "DIGITAL", 100, 0),
        ev("e10", "Dock camera", "A cassette is collected at 8:40 AM by someone with every right to be there.",
           "DIGITAL", 93, 26, "unit"),
        ev("e11", "Funding termination", "The principal investigator's funding was terminated a month earlier.",
           "DOCUMENT", 95, 18, "unit"),
        ev("e12", "Cassette destination", "The collected cassette never reached the waste contractor.",
           "DOCUMENT", 97, 34, "unit", requires=["e08", "e10"]),
    ],
    [
        tl("Three days before", "A handling routine is amended.", True, "e05"),
        tl("Two days before", "A routine firmware update is pushed.", True, "e06"),
        tl("03:00 AM", "The sample is confirmed present."),
        tl("03:12 AM", "The handling arm executes one movement.", True, "e03"),
        tl("03:40 AM", "The sample is recorded absent."),
        tl("08:40 AM", "A waste cassette is collected from the loading dock.", True, "e10"),
    ],
    ["Nobody entered the room. Ask what was already inside it.",
     "The camera showed an empty room because the room was empty.",
     "Follow the sample out of the building, not the person in."],
))

# ---------------------------------------------------------------- 014
CASES.append(case(
    14, "The Charity Accounts", "Generosity, audited",
    "Easy", "trevor",
    "The Rowan Trust", "Fraud", "Over fourteen months",
    "A small children's charity discovers a shortfall of ninety thousand pounds during "
    "its annual audit. The money left the account in forty-one payments to a supplier "
    "that provided real services, at prices nobody questioned. The trustees are "
    "volunteers and the finance function is one part-time member of staff.",
    "Trevor Lisle, the part-time finance officer, created a second supplier record "
    "with a name one character different from a genuine one, and directed forty-one "
    "payments to it. The trustee whose signature appeared on the approvals had signed "
    "blank forms in good faith, and the volunteer coordinator's cash handling errors "
    "were sloppy but honest.",
    {"approvals": "who approved the payments", "supplier": "the supplier records",
     "reconciliation": "the bank reconciliation"},
    [
        sus("trevor", "Trevor Lisle", 48, "Finance officer", "The only paid finance role",
            "Sole control of the supplier list, the payment run and the reconciliation.",
            25, ["Trevor's work laptop", "Trevor's card"],
            [st("approvals", "trustee", "Who approved the payments?",
                "Every one was approved by a trustee. The forms are on file."),
             st("supplier", "genuine", "Are the supplier records sound?",
                "They are as they have always been. I did not create any of them.", "e04", True),
             st("reconciliation", "monthly", "How is the bank reconciled?",
                "Monthly, by me, and reviewed by the treasurer.", None, True)]),
        sus("marion", "Marion Deeks", 66, "Trustee and treasurer", "Signed the approvals",
            "Her signature appears on all forty-one approval forms.",
            40, ["Marion's signature stamp"],
            [st("approvals", "signed_blank", "Who approved the payments?",
                "I signed forms. I am ashamed to say some of them were blank when I signed them."),
             st("supplier", "unaware", "Are the supplier records sound?",
                "I would not know one supplier from another."),
             st("reconciliation", "reviewed", "How is the bank reconciled?",
                "Trevor prepares it and I review it. I see a summary, not the detail.")]),
        sus("volunteer", "Nita Shah", 37, "Volunteer coordinator", "Handles cash donations",
            "Two cash reconciliations were out by small amounts.",
            35, ["Nita's cash tin"],
            [st("approvals", "not_involved", "Who approved the payments?",
                "Nothing to do with me. I handle collection tins."),
             st("supplier", "unaware", "Are the supplier records sound?",
                "I have never seen the supplier list."),
             st("reconciliation", "cash_only", "How is the bank reconciled?",
                "I reconcile the tins. Twice I have been out by a few pounds and I reported both.")]),
        sus("chair", "Douglas Mure", 59, "Chair of trustees", "Oversees governance",
            "Waived the requirement for a second approver two years ago.",
            30, ["Douglas's diary"],
            [st("approvals", "trustee", "Who approved the payments?",
                "A trustee, under the scheme of delegation. Which I now see was too loose."),
             st("supplier", "unaware", "Are the supplier records sound?",
                "That is an operational matter. I have to be able to trust it."),
             st("reconciliation", "reviewed", "How is the bank reconciled?",
                "Monthly. The treasurer reviews it and reports to the board.")]),
    ],
    [
        loc("ledger", "Accounting System", "[A]",
            "Fourteen months of entries and forty-one payments that look like all the others.",
            [search("payments", "List the payments", ["e01"], "Regular, modest, and always just under the threshold."),
             search("suppliers", "Compare the supplier records", ["e04"], "Two records, one character apart."),
             search("audittrail", "Read the system audit trail", ["e05"], "Who created the second record, and when.")]),
        loc("bankrec", "Bank Records", "[B]",
            "Statements, and a destination account that is not what it claims to be.",
            [search("destination", "Trace the destination account", ["e02"], "A personal account, not a business one."),
             search("recon", "Examine the reconciliations", ["e06"], "Prepared and reviewed, but never independently.")]),
        loc("forms", "Approval Forms", "[F]",
            "Forty-one signed forms in a lever arch file.",
            [search("signatures", "Examine the signatures", ["e03"], "Genuine, every one."),
             search("blanks", "Look for blank forms", ["e07"], "Six unused forms, already signed.")]),
        loc("cash", "Cash Handling", "[C]",
            "Tins, counting sheets, and two small discrepancies honestly reported.",
            [search("tins", "Check the cash records", ["e08"], "Out by a few pounds, twice, both reported.")]),
        loc("hr", "Personnel Records", "[P]",
            "Contracts, bank details, and the coincidences they reveal.",
            [search("details", "Compare the bank details", ["e09"], "One sort code appears in two places it should not."),
             search("delegation", "Read the scheme of delegation", ["e10"], "A waiver, minuted and forgotten.")]),
    ],
    [
        ev("e01", "Payment pattern", "Forty-one payments, each just below the second-approver threshold.",
           "DOCUMENT", 98, 12, "trevor"),
        ev("e02", "Personal destination account", "The supplier payments went to a personal current account.",
           "DOCUMENT", 97, 22),
        ev("e03", "Genuine signatures", "The trustee's signature on the approval forms is authentic.",
           "DOCUMENT", 95, 18, "marion", rh=True, cleared_by="e07"),
        ev("e04", "Near-duplicate supplier", "Two supplier records differ by a single character.",
           "DOCUMENT", 99, 26, "trevor"),
        ev("e05", "System audit trail", "The duplicate supplier record was created from the finance officer's account.",
           "DIGITAL", 100, 32, "trevor"),
        ev("e06", "Unreviewed reconciliation", "The reconciliation is prepared and reviewed without independent checking.",
           "DOCUMENT", 92, 14, "trevor"),
        ev("e07", "Pre-signed blank forms", "Six unused approval forms already carry the treasurer's signature.",
           "PHYSICAL", 94, 0),
        ev("e08", "Cash discrepancies", "Two small cash discrepancies, both self-reported.",
           "DOCUMENT", 90, 16, "volunteer", rh=True, cleared_by="e02"),
        ev("e09", "Matching bank details", "The destination sort code matches the finance officer's payroll record.",
           "DOCUMENT", 98, 34, "trevor"),
        ev("e10", "Delegation waiver", "The second-approver requirement was waived two years earlier.",
           "DOCUMENT", 93, 10, "chair", rh=True, cleared_by="e05"),
        ev("e11", "Supplier correspondence", "The genuine supplier has no record of the duplicated account.",
           "DOCUMENT", 96, 28, "trevor", requires=["e04", "e02"]),
    ],
    [
        tl("Month 1", "The second-approver requirement is waived.", True, "e10"),
        tl("Month 3", "A near-duplicate supplier record is created.", True, "e05"),
        tl("Month 4", "The first payment is made to the new supplier."),
        tl("Month 9", "A cash discrepancy is self-reported.", True, "e08"),
        tl("Month 14", "The annual audit identifies the shortfall."),
    ],
    ["Compare the supplier list against itself, character by character.",
     "A genuine signature does not mean a genuine approval.",
     "Follow the money to an account, and the account to a person."],
))

# ---------------------------------------------------------------- 015
CASES.append(case(
    15, "The Last Broadcast", "Ninety seconds that were never live",
    "Expert", "aksel",
    "Meridian Radio, Studio 3", "Blackmail and manslaughter", "10:00 PM - 11:15 PM",
    "A late-night presenter, Nora Bell, dies in her studio during a live broadcast. "
    "The programme continues for ninety seconds after the time of death established by "
    "the pathologist. Four people were in the building. The studio door logs one entry "
    "and one exit, both accounted for. The desk recording is intact and unedited.",
    "Aksel Ranta, the station's technical director, had been blackmailing Nora over a "
    "recording he held. When she told him on air that she intended to say so, he cut "
    "the live feed and substituted ninety seconds of a rehearsal recording, entering "
    "the studio during the substitution. The struggle that followed was not intended "
    "to kill her. The desk recording is intact because it records the output, not the "
    "microphone.",
    {"that_hour": "where they were between ten and eleven", "feed": "the ninety second gap",
     "recording": "the recording Nora mentioned"},
    [
        sus("aksel", "Aksel Ranta", 49, "Technical director", "Controls the transmission chain",
            "Held a recording he had been using to control her for a year.",
            25, ["Aksel's pass", "Aksel's desk drive"],
            [st("that_hour", "gallery", "Where were you between ten and eleven?",
                "In the gallery, watching the levels. I did not leave it.", None, True),
             st("feed", "no_gap", "Was there a break in the live feed?",
                "There was no break. The output is continuous, and I can prove it.", "e04", True),
             st("recording", "unaware", "What recording did she mean?",
                "I have no idea what she was referring to. She said a great many things on air.", "e09", True)]),
        sus("producer", "Deirdre Okonjo", 38, "Producer", "In the gallery",
            "Had argued with Nora about the programme's direction that evening.",
            35, ["Deirdre's script"],
            [st("that_hour", "gallery", "Where were you between ten and eleven?",
                "In the gallery until twenty past, then the edit suite."),
             st("feed", "odd", "Was there a break in the live feed?",
                "Something felt wrong around half ten. The room tone changed and then it did not."),
             st("recording", "aware", "What recording did she mean?",
                "She told me last week that somebody had something of hers. She would not say who.")]),
        sus("engineer", "Ben Croft", 27, "Duty engineer", "Maintains the studio",
            "Was in the studio corridor at the relevant time.",
            30, ["Ben's toolkit"],
            [st("that_hour", "corridor", "Where were you between ten and eleven?",
                "In the corridor and the rack room, chasing an intermittent fault."),
             st("feed", "odd", "Was there a break in the live feed?",
                "The desk did not show one. But the rack log has something at 10:31."),
             st("recording", "unaware", "What recording did she mean?",
                "No idea. I keep out of the presenters' business.")]),
        sus("guest", "Hallam Pike", 44, "Studio guest", "Left at 10:05 PM",
            "Nora had criticised him on air three weeks earlier.",
            40, ["Hallam's coat"],
            [st("that_hour", "left", "Where were you between ten and eleven?",
                "I left at five past ten. The door log will show it and so will the taxi."),
             st("feed", "not_present", "Was there a break in the live feed?",
                "I was in a car by then. I heard the programme on the radio."),
             st("recording", "unaware", "What recording did she mean?",
                "I do not know and I would rather not speculate.")]),
    ],
    [
        loc("studio", "Studio 3", "[3]",
            "A live studio, a fader left open, and a chair pushed back hard.",
            [search("desk", "Examine the mixing desk", ["e01"], "One fader open, one channel muted at source."),
             search("floors", "Search the studio floor", ["e02"], "A pass lanyard clip, snapped at the ring."),
             search("chair", "Examine the chair and table", ["e03"], "Scuffing consistent with a struggle.")]),
        loc("gallery", "Control Gallery", "[G]",
            "The room from which the output is controlled and the story is told.",
            [search("output", "Examine the output recording", ["e04"], "Continuous, unedited, ninety seconds too clean."),
             search("source", "Compare the source feed", ["e05"], "The microphone feed and the output diverge at 10:31."),
             search("rehearsal", "Find the rehearsal recording", ["e06"], "Ninety seconds of it, played out at 10:31.")]),
        loc("rack", "Rack Room", "[R]",
            "Where the transmission chain physically lives.",
            [search("racklog", "Read the rack log", ["e07"], "A source switch at 10:31 and back at 10:33."),
             search("cabling", "Inspect the cabling", ["e08"], "A patch made recently and removed badly.")]),
        loc("doorlog", "Door Access System", "[D]",
            "One entry, one exit, and a lanyard that stopped working.",
            [search("logs", "Read the studio door log", ["e10"], "One entry at 10:31, on a pass that then goes quiet."),
             search("passes", "Check the pass records", ["e11"], "One pass reported faulty the following morning.")]),
        loc("archive", "Station Archive", "[A]",
            "Where recordings that should not exist sometimes do.",
            [search("drive", "Search the technical director's drive", ["e09"], "A recording of Nora, a year old."),
             search("access", "Check the archive access log", ["e12"], "Repeated access to one file, by one account.")]),
    ],
    [
        ev("e01", "Muted source channel", "The presenter's microphone was muted at source, not at the desk.",
           "PHYSICAL", 96, 14, "aksel"),
        ev("e02", "Snapped lanyard clip", "A pass lanyard clip, snapped at the ring, on the studio floor.",
           "PHYSICAL", 88, 20, "aksel", matches=["Aksel's pass"]),
        ev("e03", "Signs of a struggle", "Scuffing at the desk consistent with a brief struggle.",
           "PHYSICAL", 94, 8),
        ev("e04", "Unedited output recording", "The transmitted output is continuous and shows no edit.",
           "DIGITAL", 100, 6),
        ev("e05", "Source and output divergence", "The microphone feed and the transmitted output diverge at 10:31.",
           "DIGITAL", 99, 26, "aksel"),
        ev("e06", "Rehearsal substitution", "Ninety seconds of a rehearsal recording were transmitted at 10:31.",
           "DIGITAL", 98, 30, "aksel"),
        ev("e07", "Rack source switch", "The transmission source was switched at 10:31 and back at 10:33.",
           "DIGITAL", 97, 24, "aksel"),
        ev("e08", "Recent patch", "A patch in the transmission chain, made recently and removed carelessly.",
           "PHYSICAL", 84, 18, "engineer", rh=True, cleared_by="e07"),
        ev("e09", "Archived recording of the presenter", "A year-old private recording of Nora, held on a technical drive.",
           "DIGITAL", 95, 28, "aksel"),
        ev("e10", "Studio door entry", "One entry to the studio at 10:31 PM.",
           "DIGITAL", 100, 22, "aksel"),
        ev("e11", "Faulty pass report", "A pass was reported faulty the following morning, its clip broken.",
           "DOCUMENT", 90, 24, "aksel"),
        ev("e12", "Archive access pattern", "One account accessed the same archived file repeatedly over a year.",
           "DIGITAL", 96, 32, "aksel", requires=["e09", "e05"]),
    ],
    [
        tl("10:00 PM", "The programme goes live."),
        tl("10:05 PM", "The studio guest leaves the building."),
        tl("10:29 PM", "The presenter refers on air to a recording she intends to discuss."),
        tl("10:31 PM", "The transmission source is switched.", True, "e07"),
        tl("10:31 PM", "The studio door records one entry.", True, "e10"),
        tl("10:33 PM", "The transmission source is switched back.", True, "e07"),
        tl("10:34 PM", "The programme continues, apparently normally."),
        tl("11:15 PM", "The presenter is found in the studio."),
    ],
    ["The output recording is intact. Ask what the output is a recording of.",
     "Ninety seconds of a live programme were not live.",
     "Somebody had something of hers. Find out where it was kept."],
))
